begin;
set local search_path=public,extensions;
select plan(46);
insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values
 ('00000000-0000-4000-8000-000000008001','phase3b.owner@serviceflow.invalid',now(),'{"display_name":"Fictional Phase Three Owner"}'),
 ('00000000-0000-4000-8000-000000008002','phase3b.other@serviceflow.invalid',now(),'{"display_name":"Fictional Other Owner"}');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-000000008001","role":"authenticated"}',true);
create temp table phase3b as select public.start_owner_onboarding() organization_id;
grant select on phase3b to anon,service_role;
select throws_ok(format('select public.publish_organization(%L)',(select organization_id from phase3b)),'22023','organization is not ready to publish','publish fails before required invariants');
select throws_ok(format('select public.complete_onboarding_review(%L)',(select organization_id from phase3b)),'22023','organization is not ready for review','review cannot complete early');
select is((select status from public.organizations where id=(select organization_id from phase3b)),'draft','failed publish leaves draft unchanged');
select lives_ok(format('select public.save_onboarding_business_identity(%L,%L,%L)',(select organization_id from phase3b),'Fictional Cedar Studio','fictional-cedar-studio'),'identity saves');
select lives_ok(format('select public.save_onboarding_location(%L,%L,%L,%L,%L)',(select organization_id from phase3b),'Europe/Bucharest','EUR','RO','Sample City'),'location saves');
select lives_ok(format('select public.save_onboarding_booking_policies(%L,120,60,1440,720,15,true,%L)',(select organization_id from phase3b),'Fictional policy.'),'policies save');
create temp table first_staff as select public.save_onboarding_staff_profile((select organization_id from phase3b),'Fictional Cedar Owner','Fictional biography.','Founder',true) id;
grant select on first_staff to service_role;
select is(public.save_onboarding_staff_profile((select organization_id from phase3b),'Fictional Cedar Owner Updated','Fictional biography.','Founder',true),(select id from first_staff),'staff retry updates the same profile');
select is((select count(*) from public.staff_profiles where organization_id=(select organization_id from phase3b)),1::bigint,'exactly one owner staff profile exists');
select is((select count(*) from public.staff_profiles sp join public.organization_memberships m on m.organization_id=sp.organization_id and m.id=sp.membership_id where sp.id=(select id from first_staff) and m.user_id='00000000-0000-4000-8000-000000008001' and sp.is_public and sp.status='active'),1::bigint,'staff profile links to authenticated owner membership');
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-000000008002","role":"authenticated"}',true);
select throws_ok(format('select public.save_onboarding_staff_profile(%L,%L,null,null,true)',(select organization_id from phase3b),'Forged Profile'),'42501','draft not found','unrelated owner cannot forge staff update');
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-000000008001","role":"authenticated"}',true);
create temp table first_service as select public.save_onboarding_service((select organization_id from phase3b),'Fictional Consultation','Fictional service.',60,15,12500) id;
grant select on first_service to service_role;
select is(public.save_onboarding_service((select organization_id from phase3b),'Fictional Consultation Updated','Fictional service.',45,10,13500),(select id from first_service),'service retry updates the same service');
select is((select count(*) from public.services where organization_id=(select organization_id from phase3b)),1::bigint,'exactly one onboarding service exists');
select is((select currency from public.services where id=(select id from first_service)),'EUR','service currency is derived from organization');
select is((select count(*) from public.service_staff where service_id=(select id from first_service) and staff_profile_id=(select id from first_staff) and is_active),1::bigint,'service is assigned to the onboarding staff profile');
select throws_ok(format('select public.replace_onboarding_availability(%L,%L::jsonb)',(select organization_id from phase3b),'[{"weekday":1,"start":"17:00","end":"09:00"}]'),'22023','invalid interval value','end before start is rejected');
select throws_ok(format('select public.replace_onboarding_availability(%L,%L::jsonb)',(select organization_id from phase3b),'[{"weekday":1,"start":"09:00","end":"12:00"},{"weekday":1,"start":"11:00","end":"13:00"}]'),'23P01','availability intervals overlap','overlapping intervals are rejected');
select throws_ok(format('select public.replace_onboarding_availability(%L,%L::jsonb)',(select organization_id from phase3b),'[{"weekday":1,"start":"09:00","end":"12:00"},{"weekday":1,"start":"09:00","end":"12:00"}]'),'23505','duplicate availability interval','duplicate intervals are rejected');
select lives_ok(format('select public.replace_onboarding_availability(%L,%L::jsonb)',(select organization_id from phase3b),'[{"weekday":1,"start":"09:00","end":"12:00"},{"weekday":3,"start":"13:00","end":"17:00"}]'),'valid schedule replacement succeeds');
select is((select count(*) from public.weekly_availability where organization_id=(select organization_id from phase3b)),2::bigint,'replacement persists the full schedule');
create temp table stable_intervals as select array_agg(id order by id) ids from public.weekly_availability where organization_id=(select organization_id from phase3b);
select lives_ok(format('select public.replace_onboarding_availability(%L,%L::jsonb)',(select organization_id from phase3b),'[{"weekday":1,"start":"09:00","end":"12:00"},{"weekday":3,"start":"13:00","end":"17:00"}]'),'schedule retry succeeds');
select is((select array_agg(id order by id) from public.weekly_availability where organization_id=(select organization_id from phase3b)),(select ids from stable_intervals),'schedule identifiers are stable across retries');
select is(public.get_public_business('fictional-cedar-studio'),null::jsonb,'draft is absent from public projection');
select lives_ok(format('select public.complete_onboarding_review(%L)',(select organization_id from phase3b)),'review completes after all prior invariants');
reset role;
set local role service_role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-000000008001","role":"service_role"}',true);
update public.onboarding_progress set review_completed_at=null where organization_id=(select organization_id from phase3b);
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-000000008001","role":"authenticated"}',true);
select throws_ok(format('select public.publish_organization(%L)',(select organization_id from phase3b)),'22023','organization is not ready to publish','publish requires completed review');
reset role;
set local role service_role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-000000008001","role":"service_role"}',true);
update public.onboarding_progress set review_completed_at=now() where organization_id=(select organization_id from phase3b);
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-000000008001","role":"authenticated"}',true);
update public.organizations set name='Untitled business' where id=(select organization_id from phase3b);
select throws_ok(format('select public.publish_organization(%L)',(select organization_id from phase3b)),'22023','organization is not ready to publish','publish requires completed identity data');
update public.organizations set name='Fictional Cedar Studio' where id=(select organization_id from phase3b);
update public.organizations set city=null where id=(select organization_id from phase3b);
select throws_ok(format('select public.publish_organization(%L)',(select organization_id from phase3b)),'22023','organization is not ready to publish','publish requires complete location data');
update public.organizations set city='Sample City' where id=(select organization_id from phase3b);
delete from public.organization_settings where organization_id=(select organization_id from phase3b);
select throws_ok(format('select public.publish_organization(%L)',(select organization_id from phase3b)),'22023','organization is not ready to publish','publish requires organization settings');
insert into public.organization_settings(organization_id,minimum_lead_minutes,booking_horizon_days,slot_interval_minutes) values((select organization_id from phase3b),120,60,15);
update public.staff_profiles set status='inactive' where id=(select id from first_staff);
select throws_ok(format('select public.publish_organization(%L)',(select organization_id from phase3b)),'22023','organization is not ready to publish','publish requires active public staff');
update public.staff_profiles set status='active' where id=(select id from first_staff);
reset role;
set local role service_role;
update public.services set status='draft' where id=(select id from first_service);
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-000000008001","role":"authenticated"}',true);
select throws_ok(format('select public.publish_organization(%L)',(select organization_id from phase3b)),'22023','organization is not ready to publish','publish requires an active service');
reset role;
set local role service_role;
update public.services set status='active' where id=(select id from first_service);
update public.service_staff set is_active=false where service_id=(select id from first_service);
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-000000008001","role":"authenticated"}',true);
select throws_ok(format('select public.publish_organization(%L)',(select organization_id from phase3b)),'22023','organization is not ready to publish','publish requires an active service assignment');
reset role;
set local role service_role;
update public.service_staff set is_active=true where service_id=(select id from first_service);
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-000000008001","role":"authenticated"}',true);
reset role;set local role service_role;delete from public.weekly_availability where organization_id=(select organization_id from phase3b);set local role authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-000000008001","role":"authenticated"}',true);
select throws_ok(format('select public.publish_organization(%L)',(select organization_id from phase3b)),'22023','organization is not ready to publish','publish requires weekly availability');
select public.replace_onboarding_availability((select organization_id from phase3b),'[{"weekday":1,"start":"09:00","end":"12:00"},{"weekday":3,"start":"13:00","end":"17:00"}]');
select is(public.publish_organization((select organization_id from phase3b)),'fictional-cedar-studio','transactional publish succeeds');
select is((select status from public.organizations where id=(select organization_id from phase3b)),'published','organization is published');
select ok((select publish_completed_at is not null from public.onboarding_progress where organization_id=(select organization_id from phase3b)),'publish progress is marked');
select is((select count(*) from public.audit_logs where organization_id=(select organization_id from phase3b) and action='organization.published'),1::bigint,'publish writes an audit event');
select is(public.publish_organization((select organization_id from phase3b)),'fictional-cedar-studio','publish retry is idempotent');
select ok(public.get_public_business('fictional-cedar-studio') is not null,'published organization is in public projection');
select ok(not (public.get_public_business('fictional-cedar-studio') ?| array['id','organizationId','email','memberships','auditLogs']),'public projection omits private identifiers and fields');
select lives_ok(format('select public.unpublish_organization(%L)',(select organization_id from phase3b)),'owner can unpublish');
select is(public.get_public_business('fictional-cedar-studio'),null::jsonb,'unpublished organization disappears from public projection');
select is(public.publish_organization((select organization_id from phase3b)),'fictional-cedar-studio','owner can safely republish');
reset role;
set local role anon;
select ok(public.get_public_business('fictional-cedar-studio') is not null,'anonymous users receive the narrow published projection');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-000000008002","role":"authenticated"}',true);
select throws_ok(format('select public.unpublish_organization(%L)',(select organization_id from phase3b)),'42501','organization not found','unrelated owner cannot unpublish');
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-000000000102","role":"authenticated"}',true);
select throws_ok(format('select public.unpublish_organization(%L)',(select organization_id from phase3b)),'42501','organization not found','staff cannot unpublish another organization');
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-000000000301","role":"authenticated"}',true);
select throws_ok($$select public.publish_organization('30000000-0000-4000-8000-000000000001')$$,'42501','organization not found','suspended organization owner cannot publish');
reset role;
set local role anon;
select throws_ok(format('select public.publish_organization(%L)',(select organization_id from phase3b)),'42501',null,'anonymous cannot publish');
select * from finish();
rollback;
