import AxeBuilder from "@axe-core/playwright";
import {expect,test} from "@playwright/test";
const email="phase3b-owner@serviceflow.test",password="Fictional-phase3b-password-12",slug="fictional-linden-studio";
async function confirmationLink(request:import("@playwright/test").APIRequestContext){for(let i=0;i<30;i++){const response=await request.get("http://127.0.0.1:54324/api/v1/messages");const body=await response.json() as {messages:{ID:string;To:{Address:string}[]}[]};const message=body.messages.find(m=>m.To.some(to=>to.Address===email));if(message){const detail=await request.get(`http://127.0.0.1:54324/api/v1/message/${message.ID}`);const mail=await detail.json() as {HTML?:string;Text?:string};const match=(mail.HTML??mail.Text??"").match(/https?:\/\/[^\s"'<>]+/);if(match)return match[0].replace(/&amp;/g,"&")}await new Promise(resolve=>setTimeout(resolve,200))}throw new Error("Fictional Phase 3B confirmation did not arrive.")}
test("owner completes, publishes, unpublishes, and republishes onboarding",async({page,request,browser})=>{
 await request.delete("http://127.0.0.1:54324/api/v1/messages");await page.goto("/auth/sign-up");await page.getByLabel("Full name").fill("Fictional Linden Owner");await page.getByLabel("Email address").fill(email);await page.getByLabel("Password",{exact:true}).fill(password);await page.getByLabel("Confirm password").fill(password);await page.getByRole("button",{name:"Create account"}).click();await page.goto(await confirmationLink(request));
 await page.getByLabel("Business display name").fill("Fictional Linden Studio");await page.getByLabel("Public address").fill(slug);await page.getByRole("button",{name:"Continue"}).click();await page.getByLabel("IANA timezone").fill("Europe/Bucharest");await page.getByLabel("Currency").selectOption("EUR");await page.getByLabel("Country code").fill("RO");await page.getByLabel("City").fill("Sample City");await page.getByRole("button",{name:"Continue"}).click();await page.getByRole("button",{name:"Continue"}).click();
 await expect(page.getByRole("heading",{name:"First staff profile"})).toBeVisible();await page.reload();await expect(page.getByRole("heading",{name:"First staff profile"})).toBeVisible();for(const width of [320,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true)}await page.emulateMedia({reducedMotion:"reduce"});await page.getByLabel("Public display name").fill("Fictional Linden Owner");await page.getByLabel("Job title (optional)").fill("Founder");await page.getByLabel("Short biography (optional)").fill("A fictional owner-operator profile used only for local testing.");await page.getByRole("button",{name:"Continue"}).click();
 await expect(page.getByRole("heading",{name:"First service"})).toBeVisible();await page.reload();await page.getByLabel("Service name").fill("Fictional Planning Session");await page.getByLabel("Description (optional)").fill("A fictional planning service.");await page.getByLabel("Duration (minutes)").fill("60");await page.getByLabel("Buffer after (minutes)").fill("15");await page.getByLabel("Price in EUR").fill("125.50");await page.getByRole("button",{name:"Continue"}).click();
 await expect(page.getByRole("heading",{name:"Weekly availability"})).toBeVisible();await page.reload();await expect(page.getByText("Europe/Bucharest",{exact:false})).toBeVisible();await page.getByLabel("Weekday").selectOption("1");await page.getByLabel("Start").fill("09:00");await page.getByLabel("End").fill("17:00");await page.getByRole("button",{name:"Add interval"}).click();await page.getByLabel("Weekday").nth(1).selectOption("3");await page.getByLabel("Start").nth(1).fill("10:00");await page.getByLabel("End").nth(1).fill("14:00");await page.getByRole("button",{name:"Continue"}).click();
 await expect(page.getByRole("heading",{name:"Review"})).toBeVisible();await page.reload();await expect(page.getByText("Fictional Planning Session")).toBeVisible();await expect(page.getByText("€125.50")).toBeVisible();await expect(page.getByText("2 weekly intervals")).toBeVisible();const preview=await page.getByRole("link",{name:"Preview your persisted draft"}).count();expect(preview).toBe(0);await page.getByRole("button",{name:"Confirm review"}).click();
 await expect(page.getByRole("heading",{name:"Publish"})).toBeVisible();await expect(page.getByRole("link",{name:"Preview your persisted draft"})).toBeVisible();const beforeContext=await browser.newContext();const anonymousBefore=await beforeContext.newPage();await anonymousBefore.goto(`/book/${slug}`);await expect(anonymousBefore.getByRole("heading",{name:"This booking page is not public."})).toBeVisible();await beforeContext.close();
 await page.getByRole("button",{name:"Publish business"}).click();await expect(page).toHaveURL(/\/dashboard\?published=1/);await expect(page.getByText("now live")).toBeVisible();await expect(page.getByRole("heading",{name:"Your business is published"})).toBeVisible();
 const anonymousContext=await browser.newContext();const anonymous=await anonymousContext.newPage();await anonymous.goto(`/book/${slug}`);await expect(anonymous.getByRole("heading",{name:"Fictional Linden Studio"})).toBeVisible();await expect(anonymous.getByRole("button",{name:"Online booking coming soon"})).toBeDisabled();for(const width of [320,390,768,1024,1440]){await anonymous.setViewportSize({width,height:900});await anonymous.reload();expect(await anonymous.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true)}const axe=await new AxeBuilder({page:anonymous}).analyze();expect(axe.violations.filter(v=>["serious","critical"].includes(v.impact??""))).toEqual([]);await anonymousContext.close();
 await page.getByRole("button",{name:"Unpublish"}).click();await expect(page.getByText("I understand the public profile")).toBeVisible();await page.getByLabel("I understand the public profile will become unavailable immediately.").check();await page.getByRole("button",{name:"Confirm unpublish"}).click();await expect(page.getByText("Business unpublished")).toBeVisible();const unavailableContext=await browser.newContext();const unavailable=await unavailableContext.newPage();await unavailable.goto(`/book/${slug}`);await expect(unavailable.getByRole("heading",{name:"This booking page is not public."})).toBeVisible();await unavailableContext.close();await page.reload();await page.getByRole("button",{name:"Republish business"}).click();await expect(page.getByText("Business republished.")).toBeVisible();
 await page.keyboard.press("Tab");await expect(page.locator(":focus-visible")).toBeVisible();
});
