import AxeBuilder from "@axe-core/playwright";
import {expect,test,type APIRequestContext,type Page} from "@playwright/test";

const password="Fictional-phase4d-password-12";
async function mailLink(request:APIRequestContext,email:string){for(let attempt=0;attempt<30;attempt++){const list=await request.get("http://127.0.0.1:54324/api/v1/messages");const body=await list.json() as {messages:{ID:string;To:{Address:string}[]}[]};const message=body.messages.find(item=>item.To.some(to=>to.Address===email));if(message){const detail=await request.get(`http://127.0.0.1:54324/api/v1/message/${message.ID}`);const mail=await detail.json() as {HTML?:string;Text?:string};const match=(mail.HTML??mail.Text??"").match(/https?:\/\/[^\s"'<>]+/);if(match)return match[0].replace(/&amp;/g,"&")}await new Promise(resolve=>setTimeout(resolve,200))}throw new Error(`Recovery email did not arrive for fictional fixture ${email}.`)}
async function recover(page:Page,request:APIRequestContext,email:string){await request.delete("http://127.0.0.1:54324/api/v1/messages");await page.goto("/auth/forgot-password");await page.getByLabel("Email address").fill(email);await page.getByRole("button",{name:"Send reset link"}).click();await page.goto(await mailLink(request,email));await page.locator("#password").fill(password);await page.locator("#confirmPassword").fill(password);await page.getByRole("button",{name:"Update password"}).click();await expect(page.locator("#form-message")).toBeVisible();await page.goto("/auth/sign-in");await page.getByLabel("Email address").fill(email);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:"Sign in"}).click();await expect(page).toHaveURL(/\/onboarding$/);await page.goto("/dashboard");await expect(page).toHaveURL(/\/dashboard$/)}

test("owner and staff use deterministic Phase 4D management lists",async({page,browser,request})=>{
 test.setTimeout(90_000);await recover(page,request,"owner.alpha@serviceflow.test");await page.goto("/dashboard/services");
 await page.getByLabel("Search services").fill("movement");await page.getByRole("button",{name:"Apply"}).click();await expect(page).toHaveURL(/q=movement/);await expect(page.getByRole("heading",{name:"Fictional Movement Session"})).toBeVisible();await page.reload();await expect(page.getByLabel("Search services")).toHaveValue("movement");
 await page.getByLabel("Search services").fill("");await page.getByLabel("Status").selectOption("archived");await page.getByRole("button",{name:"Apply"}).click();await expect(page).toHaveURL(/status=archived/);await expect(page.getByRole("heading",{name:"Posture Reset"})).toBeVisible();
 await page.getByLabel("Status").selectOption("all");await page.getByLabel("Sort by").selectOption("name");await page.getByLabel("Direction").selectOption("asc");await page.getByLabel("Per page").selectOption("5");await page.getByRole("button",{name:"Apply"}).click();await expect(page.locator(".service-list-card h2").first()).toHaveText("Balance Foundations");await page.getByLabel("Direction").selectOption("desc");await page.getByRole("button",{name:"Apply"}).click();await expect(page).toHaveURL(/dir=desc/);await expect(page.locator(".service-list-card h2").first()).toHaveText("Strength Essentials");
 await page.getByRole("link",{name:"Next"}).click();await expect(page).toHaveURL(/page=2/);await expect(page.getByText("Page 2 of 2")).toBeVisible();await page.goBack();await expect(page).not.toHaveURL(/page=2/);await page.goForward();await expect(page).toHaveURL(/page=2/);
 await page.getByLabel("Search services").fill("no deterministic match");await page.getByRole("button",{name:"Apply"}).click();await expect(page.getByRole("heading",{name:"No matching services"})).toBeVisible();await page.locator("section").getByRole("link",{name:"Reset filters"}).click();await expect(page).toHaveURL(/\/dashboard\/services$/);await expect(page.locator(".service-list-card")).toHaveCount(6);
 await page.goto("/dashboard/team?memberrole=staff&memberstatus=active&membersort=name&memberdir=desc");await expect(page.getByLabel("Role")).toHaveValue("staff");await expect(page.getByText("Sage Alpha")).toBeVisible();await page.goto("/dashboard/availability?q=sage&sort=role&dir=desc");await expect(page.getByText("Europe/Bucharest",{exact:false})).toBeVisible();await expect(page.getByText("Sage Alpha")).toBeVisible();
 await page.goto("/dashboard/services?organizationId=20000000-0000-4000-8000-000000000001&q=Strategy");await expect(page.getByRole("heading",{name:"No matching services"})).toBeVisible();await expect(page.getByText("Fictional Strategy Session")).toHaveCount(0);await page.goto("/dashboard/services/23000000-0000-4000-8000-000000000201");await expect(page.getByRole("heading",{name:"Service not found"})).toBeVisible();
 await page.goto("/dashboard/services");for(const width of [320,390,768,1024,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true)}await page.keyboard.press("Tab");await expect(page.locator(":focus-visible")).toBeVisible();const axe=await new AxeBuilder({page}).analyze();expect(axe.violations.filter(v=>["serious","critical"].includes(v.impact??""))).toEqual([]);
 const context=await browser.newContext();const staff=await context.newPage();await recover(staff,request,"staff.alpha@serviceflow.test");await staff.goto("/dashboard/services");await expect(staff.getByRole("heading",{name:"This page slipped off the schedule."})).toBeVisible();await staff.goto("/dashboard/team");await expect(staff.getByRole("heading",{name:"This page slipped off the schedule."})).toBeVisible();await staff.goto("/dashboard/availability?q=sky");await expect(staff.getByRole("heading",{name:"No matching team members"})).toBeVisible();await staff.goto("/dashboard/availability?q=sage");await expect(staff.getByText("Sage Alpha")).toBeVisible();await expect(staff.getByText("Sky Beta")).toHaveCount(0);await context.close();
});
