import AxeBuilder from "@axe-core/playwright";
import {expect,test} from "@playwright/test";
const slug="alpha-wellness-lab",service="12000000-0000-4000-8000-000000000111";
const availability=(staff="any")=>`/book/${slug}/availability?service=${service}&staff=${staff}&date=2026-09-07`;
async function openDetails(page:import("@playwright/test").Page,staff="any",slot=-1){await page.goto(availability(staff));const slots=page.locator(".slot-button");await (slot<0?slots.last():slots.nth(slot)).click();await page.getByRole("link",{name:"Continue to contact details"}).click();await expect(page.getByRole("heading",{name:"Contact details"})).toBeVisible()}
async function fill(page:import("@playwright/test").Page,email:string,name="Phase Five Fixture"){await page.getByLabel("Full name").fill(name);await page.getByLabel("Email").fill(email);await page.getByLabel("I accept the booking policy").check()}
async function latestMailLink(request:import("@playwright/test").APIRequestContext,email:string){for(let i=0;i<30;i++){const body=await (await request.get("http://127.0.0.1:54324/api/v1/messages")).json() as {messages:{ID:string;To:{Address:string}[]}[]};const message=body.messages.find(item=>item.To.some(to=>to.Address===email));if(message){const mail=await (await request.get(`http://127.0.0.1:54324/api/v1/message/${message.ID}`)).json() as {HTML?:string;Text?:string};const match=(mail.HTML??mail.Text??"").match(/https?:\/\/[^\s"'<>]+/);if(match)return match[0].replace(/&amp;/g,"&")}await new Promise(resolve=>setTimeout(resolve,200))}throw new Error("Local authentication email did not arrive.")}

test("guest completes and reloads a private no-payment confirmation",async({page})=>{const failures:string[]=[];page.on("console",m=>{if(m.type()==="error")failures.push(m.text())});page.on("requestfailed",r=>failures.push(r.url()));await openDetails(page);await fill(page,"taylor.browser@serviceflow.invalid","Taylor Browser Fixture");await page.getByLabel(/Phone/).fill("+40000000008");await page.getByRole("button",{name:"Confirm appointment"}).click();await expect(page.getByRole("heading",{name:/You’re booked with Alpha Wellness Lab/})).toBeVisible();const url=page.url();await page.reload();await expect(page).toHaveURL(url);for(const width of [320,430]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true)}await page.keyboard.press("Tab");await expect(page.locator(":focus-visible")).toBeVisible();const axe=await new AxeBuilder({page}).analyze();expect(axe.violations.filter(v=>["serious","critical"].includes(v.impact??""))).toEqual([]);expect(failures).toEqual([])});

test("invalid confirmation and invalid contact do not disclose data",async({page})=>{await page.goto(`/book/${slug}/confirmation/SF-AAAAAAAAAAAAAAAAAAAAAAAA?token=tampered-token-value-that-is-long-enough-aaaaaaaa`);await expect(page.getByRole("heading",{name:"This booking page is not public."})).toBeVisible();await openDetails(page,"any",0);await page.getByRole("button",{name:"Confirm appointment"}).click();await expect(page.getByText("Check the highlighted fields.")).toBeVisible();await expect(page.locator("#fullName-error")).toHaveText("Enter your full name.")});

test("slot loss preserves contact and offers refreshed availability",async({browser})=>{test.setTimeout(45_000);const c1=await browser.newContext(),c2=await browser.newContext(),first=await c1.newPage(),second=await c2.newPage();await openDetails(first,"13000000-0000-4000-8000-000000000102",1);await second.goto(first.url());await expect(second.getByRole("heading",{name:"Contact details"})).toBeVisible();await fill(first,"race.first@serviceflow.invalid");await fill(second,"race.second@serviceflow.invalid");await first.getByRole("button",{name:"Confirm appointment"}).click();await expect(first.getByText("Appointment confirmed")).toBeVisible();await second.getByLabel("I accept the booking policy").uncheck();await second.getByLabel("I accept the booking policy").check();await second.getByRole("button",{name:"Confirm appointment"}).click();await expect(second.getByText("That time is no longer available.")).toBeVisible();await expect(second.getByLabel("Email")).toHaveValue("race.second@serviceflow.invalid");await expect(second.getByRole("link",{name:"Return to refreshed availability"})).toBeVisible();await c1.close();await c2.close()});

test("verified client can reload confirmation without guest token",async({page,request})=>{const email="phase5b-client@serviceflow.test",password="Local-client-password-12";await request.delete("http://127.0.0.1:54324/api/v1/messages");await page.goto("/auth/sign-up");await page.getByLabel("Full name").fill("Phase Five Client");await page.getByLabel("Email address").fill(email);await page.getByLabel("Password",{exact:true}).fill(password);await page.getByLabel("Confirm password").fill(password);await page.getByRole("button",{name:"Create account"}).click();await page.goto(await latestMailLink(request,email));await openDetails(page,"any",2);await fill(page,email,"Phase Five Client");await page.getByRole("button",{name:"Confirm appointment"}).click();await expect(page.getByText("Appointment confirmed")).toBeVisible();await page.goto(page.url().replace(/\?token=.*/,""));await expect(page.getByRole("heading",{name:/You’re booked with Alpha Wellness Lab/})).toBeVisible()});
