import AxeBuilder from "@axe-core/playwright";
import {expect,test} from "@playwright/test";
const email="phase3a-owner@serviceflow.test",password="Fictional-owner-password-12";
async function confirmationLink(request:import("@playwright/test").APIRequestContext){for(let i=0;i<30;i++){const response=await request.get("http://127.0.0.1:54324/api/v1/messages");const body=await response.json() as {messages:{ID:string;To:{Address:string}[]}[]};const message=body.messages.find(m=>m.To.some(to=>to.Address===email));if(message){const detail=await request.get(`http://127.0.0.1:54324/api/v1/message/${message.ID}`);const mail=await detail.json() as {HTML?:string;Text?:string};const match=(mail.HTML??mail.Text??"").match(/https?:\/\/[^\s"'<>]+/);if(match)return match[0].replace(/&amp;/g,"&")}await new Promise(resolve=>setTimeout(resolve,200))}throw new Error("Fictional onboarding confirmation did not arrive.")}
test("verified owner saves and resumes the Phase 3A onboarding foundation",async({page,request})=>{
 await request.delete("http://127.0.0.1:54324/api/v1/messages");await page.goto("/auth/sign-up");await page.getByLabel("Full name").fill("Fictional Phase Three Owner");await page.getByLabel("Email address").fill(email);await page.getByLabel("Password",{exact:true}).fill(password);await page.getByLabel("Confirm password").fill(password);await page.getByRole("button",{name:"Create account"}).click();await page.goto(await confirmationLink(request));
 await expect(page.getByRole("heading",{name:"Business identity"})).toBeVisible();await page.getByLabel("Business display name").fill("Fictional Juniper Studio");await page.getByLabel("Public address").fill("admin");await page.getByRole("button",{name:"Continue"}).click();await expect(page.getByText("This address is reserved.")).toBeVisible();await page.getByLabel("Business display name").fill("Fictional Juniper Studio");await page.getByLabel("Public address").fill("fictional-juniper-studio");await page.getByRole("button",{name:"Continue"}).click();await expect(page.getByRole("heading",{name:"Location & region"})).toBeVisible();
 await page.reload();await expect(page.getByRole("heading",{name:"Location & region"})).toBeVisible();await page.getByLabel("IANA timezone").fill("Europe/Bucharest");await page.getByLabel("Currency").selectOption("RON");await page.getByLabel("Country code").fill("RO");await page.getByLabel("City").fill("Sample City");await page.getByRole("button",{name:"Continue"}).click();await expect(page.getByRole("heading",{name:"Booking policies"})).toBeVisible();await page.getByLabel("Minimum lead time (minutes)").fill("120");await page.getByLabel("Booking horizon (days)").fill("60");await page.getByLabel("Cancellation notice (minutes)").fill("1440");await page.getByLabel("Reschedule notice (minutes)").fill("720");await page.getByLabel("Slot interval (minutes)").fill("15");await page.getByRole("button",{name:"Continue"}).click();await expect(page.getByRole("heading",{name:"First staff profile"})).toBeVisible();
 await page.getByRole("button",{name:"Sign out"}).click();await page.getByLabel("Email address").fill(email);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:"Sign in"}).click();await expect(page.getByRole("heading",{name:"First staff profile"})).toBeVisible();
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});await page.reload();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true)}const axe=await new AxeBuilder({page}).analyze();expect(axe.violations.filter(v=>["serious","critical"].includes(v.impact??""))).toEqual([]);await page.keyboard.press("Tab");await expect(page.locator(":focus-visible")).toBeVisible();
 await page.goto("/dashboard");await expect(page.getByRole("heading",{name:"This page slipped off the schedule."})).toBeVisible();
});
