import AxeBuilder from "@axe-core/playwright";
import {expect,test} from "@playwright/test";
test("owner appointment workspace is tenant-safe, shareable, responsive, and accessible",async({page,browser})=>{
 test.setTimeout(90_000);
 await page.goto("/auth/sign-in");await page.getByLabel("Email address").fill("owner.beta@serviceflow.invalid");await page.getByLabel("Password").fill("Fictional-phase6a-password-12");await page.getByRole("button",{name:"Sign in"}).click();await expect(page).toHaveURL(/onboarding$/);
 await page.goto("/dashboard");await expect(page.getByRole("heading",{name:"Appointment activity"})).toBeVisible();await page.goto("/dashboard/appointments?view=calendar&status=confirmed");await expect(page.locator(".calendar-agenda")).toBeVisible();await expect(page.getByLabel("View")).toHaveValue("calendar");await page.locator(".appointment-card").getByRole("link",{name:"View details"}).click();await expect(page).toHaveURL(/dashboard\/appointments\/[0-9a-f-]+/);await expect(page.locator(".detail-grid")).toContainText("Fictional Strategy Session");await page.getByRole("link",{name:/Back to appointments/}).click();await expect(page).toHaveURL(/view=calendar/);
 await page.goto("/dashboard/appointments?from=bad");await expect(page.getByText(/unsupported query values/)).toBeVisible();await page.getByLabel("Search clients or reference").fill("no match");await page.getByRole("button",{name:"Apply filters"}).click();await expect(page.getByRole("heading",{name:"No matching appointments"})).toBeVisible();await page.goto("/dashboard/appointments/19000000-0000-4000-8000-000000000101");await expect(page.getByRole("heading",{name:/slipped off the schedule/i})).toBeVisible();
 await page.goto("/dashboard/appointments");for(const width of [1440,430,320]){await page.setViewportSize({width,height:900});await page.reload();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true)}await page.keyboard.press("Tab");await expect(page.locator(":focus-visible")).toBeVisible();const axe=await new AxeBuilder({page}).analyze();expect(axe.violations.filter(v=>["serious","critical"].includes(v.impact??""))).toEqual([]);
 const anonymous=await browser.newPage();await anonymous.goto("/dashboard/appointments");await expect(anonymous).toHaveURL(/auth\/sign-in/);await anonymous.close();
});
