import {z} from "zod";
import type {RawSearchParams} from "@/features/lists/query";
const scalar=(value:string|string[]|undefined)=>typeof value==="string"?value:undefined;
const localDate=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(value=>!Number.isNaN(Date.parse(`${value}T00:00:00Z`))).catch("");
const schema=z.object({q:z.string().trim().max(100).catch(""),status:z.enum(["all","pending_payment","confirmed","completed","cancelled","no_show"]).catch("all"),service:z.union([z.string().uuid(),z.literal("")]).catch(""),staff:z.union([z.string().uuid(),z.literal("")]).catch(""),from:localDate,to:localDate,view:z.enum(["list","calendar"]).catch("list"),sort:z.enum(["start","client","service","created"]).catch("start"),dir:z.enum(["asc","desc"]).catch("asc"),page:z.coerce.number().int().min(1).max(10000).catch(1),size:z.coerce.number().int().pipe(z.union([z.literal(5),z.literal(10),z.literal(20)])).catch(10)});
export type AppointmentQuery=z.infer<typeof schema>;
export function parseAppointmentQuery(raw:RawSearchParams){const value=schema.parse(Object.fromEntries(Object.keys(schema.shape).map(key=>[key,scalar(raw[key])])));if(value.from&&value.to&&value.from>value.to)return {...value,from:"",to:""};return value}
export function hasInvalidAppointmentQuery(raw:RawSearchParams,parsed:AppointmentQuery){const known=new Set(Object.keys(schema.shape));if(Object.keys(raw).some(key=>!known.has(key)||Array.isArray(raw[key])))return true;const normalized:Record<string,string>={...parsed,page:String(parsed.page),size:String(parsed.size)};return Object.entries(raw).some(([key,value])=>typeof value==="string"&&value!==""&&normalized[key]!==value.trim())}
export function appointmentState(query:AppointmentQuery,patch:Partial<AppointmentQuery>={}){return {...query,...patch}}
export function groupAppointments<T extends {starts_at:string}>(items:T[],timezone:string){const formatter=new Intl.DateTimeFormat("en-CA",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit"});return items.reduce<Record<string,T[]>>((groups,item)=>{const day=formatter.format(new Date(item.starts_at));(groups[day]??=[]).push(item);return groups},{})}
export function localDayBounds(date:string,timezone:string){const parts=(instant:Date)=>new Intl.DateTimeFormat("en-CA",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(instant);const convert=(day:string)=>{let guess=new Date(`${day}T00:00:00Z`);for(let i=0;i<3;i++){const map=Object.fromEntries(parts(guess).map(p=>[p.type,p.value]));const represented=Date.UTC(+map.year,+map.month-1,+map.day,+map.hour,+map.minute,+map.second);guess=new Date(guess.getTime()+(Date.parse(`${day}T00:00:00Z`)-represented))}return guess.toISOString()};const next=new Date(`${date}T00:00:00Z`);next.setUTCDate(next.getUTCDate()+1);return {start:convert(date),end:convert(next.toISOString().slice(0,10))}}
export function aggregateAppointmentStatuses(statuses:string[]){return statuses.reduce((value,status)=>({...value,completed:value.completed+(status==="completed"?1:0),cancelled:value.cancelled+(["cancelled","no_show"].includes(status)?1:0),active:value.active+(["confirmed","pending_payment"].includes(status)?1:0)}),{active:0,completed:0,cancelled:0})}
