import "server-only";
import {notFound} from "next/navigation";
import {z} from "zod";
import {boundedPage} from "@/features/lists/query";
import {getOwnerWorkspace} from "@/features/services/workspace";
import type {AppointmentQuery} from "./query";
type RpcClient={rpc(name:string,args:Record<string,unknown>):PromiseLike<{data:unknown;error:unknown}>};
const item=z.object({id:z.string().uuid(),public_reference:z.string(),status:z.string(),starts_at:z.string(),ends_at:z.string(),created_at:z.string(),service_name_snapshot:z.string(),staff_name_snapshot:z.string(),client_name_snapshot:z.string(),client_email_snapshot:z.string(),duration_minutes_snapshot:z.number(),price_minor_snapshot:z.number(),currency_snapshot:z.string(),payment_mode_snapshot:z.string()});
const listSchema=z.object({timezone:z.string(),items:z.array(item),total:z.number(),organizationTotal:z.number()});
const overviewSchema=z.object({timezone:z.string(),localDate:z.string(),today:z.number(),upcoming:z.number(),completed:z.number(),cancelled:z.number(),schedule:z.array(z.object({id:z.string().uuid(),reference:z.string(),startsAt:z.string(),status:z.string(),service:z.string(),staff:z.string(),client:z.string()}))});
const detailSchema=z.object({id:z.string().uuid(),reference:z.string(),status:z.string(),startsAt:z.string(),endsAt:z.string(),bufferEndsAt:z.string(),service:z.string(),staff:z.string(),durationMinutes:z.number(),bufferMinutes:z.number(),priceMinor:z.number(),currency:z.string(),paymentMode:z.string(),depositMinor:z.number().nullable(),clientName:z.string(),clientEmail:z.string(),clientPhone:z.string().nullable(),timezone:z.string(),policyText:z.string(),policyVersion:z.string(),policyAcceptedAt:z.string(),createdAt:z.string(),updatedAt:z.string(),events:z.array(z.object({id:z.string().uuid(),type:z.string(),actorType:z.string(),occurredAt:z.string()})),notifications:z.array(z.object({id:z.string().uuid(),channel:z.string(),template:z.string(),status:z.string(),scheduledFor:z.string(),createdAt:z.string()}))});
export async function getAppointmentOverview(){const {db,organization}=await getOwnerWorkspace();const {data,error}=await (db as unknown as RpcClient).rpc("get_owner_appointment_overview",{target_org_id:organization.id});const parsed=overviewSchema.safeParse(data);if(error||!parsed.success)throw new Error("Appointment overview could not be loaded.");return {db,organization,overview:parsed.data}}
export async function getAppointmentList(query:AppointmentQuery){const {db,organization}=await getOwnerWorkspace();const run=async(page:number)=>(db as unknown as RpcClient).rpc("list_owner_appointments",{target_org_id:organization.id,search_text:query.q,status_filter:query.status,service_filter:query.service||null,staff_filter:query.staff||null,date_from:query.from||null,date_to:query.to||null,sort_field:query.sort,sort_direction:query.dir,target_limit:query.size,target_offset:(page-1)*query.size});let page=query.page,response=await run(page),parsed=listSchema.safeParse(response.data);if(response.error||!parsed.success)throw new Error("Appointments could not be loaded.");const safe=boundedPage(page,parsed.data.total,query.size);if(safe!==page){page=safe;response=await run(page);parsed=listSchema.safeParse(response.data);if(response.error||!parsed.success)throw new Error("Appointments could not be loaded.")}const [{data:services},{data:staff}]=await Promise.all([db.from("services").select("id,name").eq("organization_id",organization.id).order("name"),db.from("staff_profiles").select("id,display_name").eq("organization_id",organization.id).order("display_name")]);return {organization,result:{...parsed.data,page,pageSize:query.size},services:services??[],staff:staff??[]}}
export async function getAppointmentDetail(id:string){if(!z.string().uuid().safeParse(id).success)notFound();const {db,organization}=await getOwnerWorkspace();const {data,error}=await (db as unknown as RpcClient).rpc("get_owner_appointment_detail",{target_org_id:organization.id,target_appointment_id:id});const parsed=detailSchema.safeParse(data);if(error||!parsed.success)notFound();return {organization,appointment:parsed.data}}
