"use server";
import {revalidatePath} from "next/cache";import {createClient} from "@/lib/supabase/server";import type {AvailabilityActionResult} from "./action-result";import {createBlockSchema,createWeeklySchema,deleteBlockSchema,deleteWeeklySchema,updateBlockSchema,updateWeeklySchema} from "./schemas";import {zonedLocalToUtc} from "./time";import {getAvailabilityWorkspace} from "./workspace";
const raw=(d:FormData)=>Object.fromEntries([...d.entries()].filter(([k])=>!k.startsWith("$ACTION_")));
const invalid=(e:{flatten():{fieldErrors:Record<string,string[]|undefined>}}):AvailabilityActionResult=>({status:"error",code:"VALIDATION_FAILED",message:"Check the highlighted fields.",fields:e.flatten().fieldErrors});
async function client(){const db=await createClient();const{data}=await db.auth.getUser();return data.user?.email_confirmed_at?db:null}
function done(staff:string,message:string){revalidatePath("/dashboard/availability");revalidatePath(`/dashboard/availability/${staff}`);revalidatePath("/book/[slug]","page");return{status:"success",message} as AvailabilityActionResult}
function failure(error:{code?:string}|null):AvailabilityActionResult{return{status:"error",code:error?.code==="40001"?"STALE":error?.code==="23P01"?"CONFLICT":"UNAVAILABLE",message:error?.code==="40001"?"This schedule changed elsewhere. Reload before trying again.":error?.code==="23P01"?"Weekly intervals cannot overlap.":"We could not update this schedule."}}
export async function createWeekly(_:AvailabilityActionResult,d:FormData){const p=createWeeklySchema.safeParse(raw(d));if(!p.success)return invalid(p.error);const db=await client();if(!db)return failure(null);const{error}=await db.rpc("create_weekly_availability",{target_staff_profile_id:p.data.staffProfileId,target_weekday:p.data.weekday,target_start:p.data.start,target_end:p.data.end});return error?failure(error):done(p.data.staffProfileId,"Availability interval added.")}
export async function updateWeekly(_:AvailabilityActionResult,d:FormData){const p=updateWeeklySchema.safeParse(raw(d));if(!p.success)return invalid(p.error);const db=await client();if(!db)return failure(null);const{error}=await db.rpc("update_weekly_availability",{target_interval_id:p.data.intervalId,target_weekday:p.data.weekday,target_start:p.data.start,target_end:p.data.end,expected_updated_at:p.data.expectedUpdatedAt});return error?failure(error):done(p.data.staffProfileId,"Availability interval updated.")}
export async function deleteWeekly(_:AvailabilityActionResult,d:FormData){const p=deleteWeeklySchema.safeParse(raw(d));if(!p.success)return invalid(p.error);const db=await client();if(!db)return failure(null);const{error}=await db.rpc("delete_weekly_availability",{target_interval_id:p.data.intervalId,expected_updated_at:p.data.expectedUpdatedAt});return error?failure(error):done(p.data.staffProfileId,"Availability interval removed.")}
async function blockInput(d:FormData){const w=await getAvailabilityWorkspace();const start=zonedLocalToUtc(String(d.get("startsAt")??""),w.organization.timezone),end=zonedLocalToUtc(String(d.get("endsAt")??""),w.organization.timezone);return{start,end}}
export async function createBlock(_:AvailabilityActionResult,d:FormData){const p=createBlockSchema.safeParse(raw(d));if(!p.success)return invalid(p.error);const t=await blockInput(d);if(!t.start||!t.end||t.start>=t.end)return{status:"error",code:"VALIDATION_FAILED",message:"Use an unambiguous local time and make the end later than the start.",fields:{endsAt:["Check this interval, including daylight-saving transitions."]}} as AvailabilityActionResult;const db=await client();if(!db)return failure(null);const{error}=await db.rpc("create_blocked_time",{target_staff_profile_id:p.data.staffProfileId,target_starts_at:t.start,target_ends_at:t.end,target_reason:p.data.reason});return error?failure(error):done(p.data.staffProfileId,"Blocked time added.")}
export async function updateBlock(_:AvailabilityActionResult,d:FormData){const p=updateBlockSchema.safeParse(raw(d));if(!p.success)return invalid(p.error);const t=await blockInput(d);if(!t.start||!t.end||t.start>=t.end)return{status:"error",code:"VALIDATION_FAILED",message:"Use an unambiguous local time and make the end later than the start."} as AvailabilityActionResult;const db=await client();if(!db)return failure(null);const{error}=await db.rpc("update_blocked_time",{target_block_id:p.data.blockId,target_starts_at:t.start,target_ends_at:t.end,target_reason:p.data.reason,expected_updated_at:p.data.expectedUpdatedAt});return error?failure(error):done(p.data.staffProfileId,"Blocked time updated.")}
export async function deleteBlock(_:AvailabilityActionResult,d:FormData){const p=deleteBlockSchema.safeParse(raw(d));if(!p.success)return invalid(p.error);const db=await client();if(!db)return failure(null);const{error}=await db.rpc("delete_blocked_time",{target_block_id:p.data.blockId,expected_updated_at:p.data.expectedUpdatedAt});return error?failure(error):done(p.data.staffProfileId,"Blocked time removed.")}
