"use client";
import {useActionState} from "react";import {createBlock,createWeekly,deleteBlock,deleteWeekly,updateBlock,updateWeekly} from "@/features/availability/actions";import {initialAvailabilityResult,type AvailabilityActionResult} from "@/features/availability/action-result";
const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
function Notice({state}:{state:AvailabilityActionResult}){return state.message?<p className={state.status==="success"?"form-success":"form-error"} role={state.status==="error"?"alert":"status"} aria-live="polite">{state.message}</p>:null}
function Submit({children,pending,danger=false}:{children:string;pending:boolean;danger?:boolean}){return <button className={`button ${danger?"danger-button":"button-primary"}`} disabled={pending}>{pending?"Saving…":children}</button>}
function WeeklyFields({weekday=1,start="09:00",end="17:00"}:{weekday?:number;start?:string;end?:string}){return <><label className="form-field"><span>Weekday</span><select name="weekday" defaultValue={weekday}>{days.map((day,index)=><option key={day} value={index+1}>{day}</option>)}</select></label><label className="form-field"><span>Start</span><input name="start" type="time" step="300" defaultValue={start} required/></label><label className="form-field"><span>End</span><input name="end" type="time" step="300" defaultValue={end} required/></label></>}
export function AddWeeklyForm({staffProfileId}:{staffProfileId:string}){const[state,action,pending]=useActionState(createWeekly,initialAvailabilityResult);return <form action={action} className="schedule-form"><input type="hidden" name="staffProfileId" value={staffProfileId}/><WeeklyFields/><Submit pending={pending}>Add interval</Submit><Notice state={state}/></form>}
export function WeeklyRow({item,staffProfileId}:{item:{id:string;weekday:number;start_local:string;end_local:string;updated_at:string};staffProfileId:string}){const[u,ua,up]=useActionState(updateWeekly,initialAvailabilityResult);const[d,da,dp]=useActionState(deleteWeekly,initialAvailabilityResult);return <article className="schedule-item"><form action={ua} className="schedule-form"><input type="hidden" name="staffProfileId" value={staffProfileId}/><input type="hidden" name="intervalId" value={item.id}/><input type="hidden" name="expectedUpdatedAt" value={item.updated_at}/><WeeklyFields weekday={item.weekday} start={item.start_local.slice(0,5)} end={item.end_local.slice(0,5)}/><Submit pending={up}>Save</Submit><Notice state={u}/></form><form action={da} onSubmit={event=>{if(!confirm("Remove this weekly interval?"))event.preventDefault()}}><input type="hidden" name="staffProfileId" value={staffProfileId}/><input type="hidden" name="intervalId" value={item.id}/><input type="hidden" name="expectedUpdatedAt" value={item.updated_at}/><Submit pending={dp} danger>Remove interval</Submit><Notice state={d}/></form></article>}
function BlockFields({start="",end="",reason=""}:{start?:string;end?:string;reason?:string}){return <><label className="form-field"><span>Starts</span><input name="startsAt" type="datetime-local" defaultValue={start} required/></label><label className="form-field"><span>Ends</span><input name="endsAt" type="datetime-local" defaultValue={end} required/></label><label className="form-field schedule-reason"><span>Internal label <small>(optional)</small></span><input name="reason" maxLength={500} defaultValue={reason} autoComplete="off"/></label></>}
export function AddBlockForm({staffProfileId}:{staffProfileId:string}){const[state,action,pending]=useActionState(createBlock,initialAvailabilityResult);return <form action={action} className="schedule-form block-form"><input type="hidden" name="staffProfileId" value={staffProfileId}/><BlockFields/><Submit pending={pending}>Add blocked time</Submit><Notice state={state}/></form>}
export function BlockRow({item,start,end,staffProfileId}:{item:{id:string;reason:string|null;updated_at:string};start:string;end:string;staffProfileId:string}){const[u,ua,up]=useActionState(updateBlock,initialAvailabilityResult);const[d,da,dp]=useActionState(deleteBlock,initialAvailabilityResult);return <article className="schedule-item"><form action={ua} className="schedule-form block-form"><input type="hidden" name="staffProfileId" value={staffProfileId}/><input type="hidden" name="blockId" value={item.id}/><input type="hidden" name="expectedUpdatedAt" value={item.updated_at}/><BlockFields start={start} end={end} reason={item.reason??""}/><Submit pending={up}>Save</Submit><Notice state={u}/></form><form action={da} onSubmit={event=>{if(!confirm("Remove this blocked time?"))event.preventDefault()}}><input type="hidden" name="staffProfileId" value={staffProfileId}/><input type="hidden" name="blockId" value={item.id}/><input type="hidden" name="expectedUpdatedAt" value={item.updated_at}/><Submit pending={dp} danger>Remove block</Submit><Notice state={d}/></form></article>}
