"use client";
import { useActionState, useState } from "react";
import { acceptInvitation, changeMemberStatus, inviteTeamMember, resendInvitation, revokeInvitation, updateMemberProfile } from "@/features/team/actions";
import { initialTeamResult } from "@/features/team/action-result";
import type { TeamMember } from "@/features/team/model";

function Message({ state }: { state: typeof initialTeamResult & { message?: string } }) {
  return state.message ? <p className={`auth-message auth-message-${state.status}`} role={state.status === "error" ? "alert" : "status"} aria-live="polite">{state.message}</p> : null;
}
export function InvitationForm({ organizationId }: { organizationId: string }) {
  const [state, action, pending] = useActionState(inviteTeamMember, initialTeamResult);
  return <form action={action} className="service-form" noValidate><input type="hidden" name="organizationId" value={organizationId}/><div className="form-field"><label htmlFor="email">Work email</label><input id="email" name="email" type="email" autoComplete="email" required aria-invalid={Boolean(state.fields?.email)} aria-describedby={state.fields?.email ? "email-error" : "email-hint"}/><p id="email-hint" className="field-hint">The invitation grants staff access only and expires after seven days.</p>{state.fields?.email ? <p id="email-error" className="field-error" role="alert">{state.fields.email.join(" ")}</p> : null}</div><Message state={state}/><button className="button button-primary" disabled={pending}>{pending ? "Sending…" : "Send invitation"}</button></form>;
}
export function InvitationControls({ invitationId }: { invitationId: string }) {
  const [resendState, resendAction, resendPending] = useActionState(resendInvitation, initialTeamResult);
  const [revokeState, revokeAction, revokePending] = useActionState(revokeInvitation, initialTeamResult);
  const [confirming, setConfirming] = useState(false);
  return <div className="invitation-actions"><form action={resendAction}><input type="hidden" name="invitationId" value={invitationId}/><button className="button onboarding-secondary" disabled={resendPending}>{resendPending ? "Sending…" : "Resend"}</button><Message state={resendState}/></form>{confirming ? <div className="confirmation-panel" role="group" aria-label="Confirm invitation revocation"><p>Revoke this invitation? Its link will stop working immediately.</p><form action={revokeAction}><input type="hidden" name="invitationId" value={invitationId}/><button className="button danger-button" disabled={revokePending}>{revokePending ? "Revoking…" : "Confirm revoke"}</button></form><button type="button" className="button onboarding-secondary" onClick={() => setConfirming(false)}>Keep invitation</button><Message state={revokeState}/></div> : <button type="button" className="button danger-outline" onClick={() => setConfirming(true)}>Revoke</button>}</div>;
}
export function MemberProfileForm({ member }: { member: TeamMember }) {
  const [state, action, pending] = useActionState(updateMemberProfile, initialTeamResult);
  const error = (field: "displayName" | "jobTitle" | "bio") => state.fields?.[field]?.join(" ");
  return <form action={action} className="service-form" noValidate><input type="hidden" name="membershipId" value={member.membershipId}/><input type="hidden" name="expectedUpdatedAt" value={member.profileUpdatedAt ?? ""}/><TeamField name="displayName" label="Display name" value={member.displayName ?? ""} required error={error("displayName")}/><TeamField name="jobTitle" label="Professional title" value={member.jobTitle ?? ""} error={error("jobTitle")}/><div className="form-field"><label htmlFor="bio">Short biography</label><textarea id="bio" name="bio" rows={6} maxLength={2000} defaultValue={member.bio ?? ""} aria-invalid={Boolean(error("bio"))}/>{error("bio") ? <p className="field-error" role="alert">{error("bio")}</p> : null}</div><input type="hidden" name="isPublic" value="false"/><label className="checkbox-field"><input type="checkbox" name="isPublic" value="true" defaultChecked={member.isPublic ?? false}/><span><strong>Show on the public business profile</strong><small>Inactive members are never shown or eligible for new assignments.</small></span></label><Message state={state}/><button className="button button-primary" disabled={pending}>{pending ? "Saving…" : "Save profile"}</button></form>;
}
function TeamField({ name, label, value, required, error }: { name: string; label: string; value: string; required?: boolean; error?: string }) { return <div className="form-field"><label htmlFor={name}>{label}{required ? " *" : ""}</label><input id={name} name={name} defaultValue={value} required={required} maxLength={100} aria-invalid={Boolean(error)}/>{error ? <p className="field-error" role="alert">{error}</p> : null}</div>; }
export function MemberStatusControl({ member }: { member: TeamMember }) {
  const [state, action, pending] = useActionState(changeMemberStatus, initialTeamResult); const [confirming, setConfirming] = useState(false); const next = member.membershipStatus === "active" ? "inactive" : "active";
  if (next === "active") return <form action={action}><input type="hidden" name="membershipId" value={member.membershipId}/><input type="hidden" name="status" value="active"/><button className="button button-primary" disabled={pending}>{pending ? "Activating…" : "Activate member"}</button><Message state={state}/></form>;
  return confirming ? <div className="confirmation-panel"><p><strong>Deactivate {member.displayName}?</strong></p><p>They will lose team access and all active service assignments will be switched off. Historical records remain.</p><form action={action}><input type="hidden" name="membershipId" value={member.membershipId}/><input type="hidden" name="status" value="inactive"/><button className="button danger-button" disabled={pending}>{pending ? "Deactivating…" : "Confirm deactivation"}</button></form><button className="button onboarding-secondary" type="button" onClick={() => setConfirming(false)}>Cancel</button><Message state={state}/></div> : <button className="button danger-outline" type="button" onClick={() => setConfirming(true)}>Deactivate member</button>;
}
export function AcceptInvitationForm({ invitationId }: { invitationId: string }) { const [state, action, pending] = useActionState(acceptInvitation, initialTeamResult); return <form action={action} className="auth-form"><input type="hidden" name="invitationId" value={invitationId}/><Message state={state}/><button className="button button-primary button-full" disabled={pending}>{pending ? "Joining…" : "Accept and join team"}</button></form>; }
