import {randomUUID} from "node:crypto";
import Link from "next/link";
import {notFound} from "next/navigation";
import {BookingForm} from "@/features/booking/booking-form";
import {createGuestToken} from "@/features/booking/booking";
import {getBookingPolicy} from "@/features/booking/booking-server";
import {getAvailability} from "@/features/booking/server";
import {localDateSchema,publicSlugSchema} from "@/features/booking/schemas";
import {getPublicBusiness} from "@/features/onboarding/public-business";
import {formatMinorPrice} from "@/features/onboarding/schemas";
type Props={params:Promise<{slug:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>};
const one=(value:string|string[]|undefined)=>typeof value==="string"?value:"";
export default async function Page({params,searchParams}:Props){const slug=publicSlugSchema.safeParse((await params).slug);if(!slug.success)notFound();const business=await getPublicBusiness(slug.data);if(!business)notFound();const query=await searchParams,serviceId=one(query.service),staff=one(query.staff)||"any",date=one(query.date),startsAt=one(query.slot);const service=business.services.find(item=>item.id===serviceId&&item.paymentMode==="none");if(!service||!localDateSchema.safeParse(date).success)return <Invalid slug={business.slug}/>;const availability=await getAvailability(business.slug,service.id,staff==="any"?null:staff,date);const slot=availability?.slots.find(item=>item.startsAt===startsAt&&(staff==="any"||item.staffIds.includes(staff)));const policy=await getBookingPolicy(business.slug,service.id);if(!slot||!availability||!policy)return <Invalid slug={business.slug} service={service.id} staff={staff} date={date}/>;const staffName=staff==="any"?"Any available team member (assigned when confirmed)":availability.context.staff.find(item=>item.id===staff)?.displayName;if(!staffName)return <Invalid slug={business.slug}/>;const display=new Intl.DateTimeFormat("en",{timeZone:business.timezone,weekday:"long",year:"numeric",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(new Date(slot.startsAt));const recoveryUrl=`/book/${business.slug}/availability?service=${service.id}&staff=${encodeURIComponent(staff)}&date=${date}`;return <main id="main-content" className="booking-page"><header className="booking-header"><Link className="brand-link" href="/">ServiceFlow</Link><Link href={recoveryUrl}>Change time</Link></header><section className="booking-shell"><p className="eyebrow">Review and confirm</p><h1>Contact details</h1><p>Your appointment is confirmed only after the server checks this time again.</p><section className="booking-review" aria-labelledby="review-heading"><h2 id="review-heading">Appointment summary</h2><dl><div><dt>Business</dt><dd>{business.name}</dd></div><div><dt>Service</dt><dd>{service.name}</dd></div><div><dt>Team member</dt><dd>{staffName}</dd></div><div><dt>Local time</dt><dd>{display}</dd></div><div><dt>Duration</dt><dd>{service.durationMinutes} minutes</dd></div><div><dt>Price</dt><dd>{formatMinorPrice(service.priceMinor,business.currency)} · No online payment</dd></div><div><dt>Timezone</dt><dd>{business.timezone}</dd></div></dl></section><BookingForm hidden={{slug:business.slug,serviceId:service.id,staff,date,startsAt:slot.startsAt,submissionKey:randomUUID(),guestToken:createGuestToken()}} policy={policy.text} recoveryUrl={recoveryUrl}/></section></main>}
function Invalid({slug,service,staff,date}:{slug:string;service?:string;staff?:string;date?:string}){const href=service&&staff&&date?`/book/${slug}/availability?service=${service}&staff=${encodeURIComponent(staff)}&date=${date}`:`/book/${slug}`;return <main id="main-content" className="booking-page"><section className="booking-shell"><div className="auth-message auth-message-error" role="alert">That booking selection is no longer valid.</div><h1>Choose another time</h1><p>No appointment was created.</p><Link className="button button-ink" href={href}>Return to availability</Link></section></main>}
