import Link from "next/link";
import {MediaControl} from "@/components/onboarding/media-control";
import {PublicationManager} from "@/components/onboarding/publication-manager";
import {signOutAction} from "@/features/auth/actions";
import {getAuthContext} from "@/features/auth/context";
import {getAppointmentOverview} from "@/features/appointments/workspace";
import {getPublicEnvironment} from "@/lib/env/public";
import {createClient} from "@/lib/supabase/server";
const time=(value:string,zone:string)=>new Intl.DateTimeFormat("en",{timeZone:zone,month:"short",day:"numeric",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(new Date(value));
export const metadata={title:"Owner dashboard"};
export default async function Page({searchParams}:{searchParams:Promise<{published?:string;joined?:string}>}){
 const context=await getAuthContext(),membership=context?.activeMemberships[0],query=await searchParams;if(membership?.role==="staff"){const db=await createClient(),{data:organization}=await db.from("organizations").select("name,timezone").eq("id",membership.organizationId).single();return <main id="main-content" className="dashboard-foundation"><header className="dashboard-header"><div><p className="eyebrow">Staff workspace</p><h1>{organization?.name??"Workspace"}</h1><p>Schedule times use {organization?.timezone??"the business timezone"}.</p></div><form action={signOutAction}><button className="button onboarding-secondary">Sign out</button></form></header>{query.joined==="1"?<div className="publish-success" role="status">Invitation accepted. Welcome to the team.</div>:null}<nav className="owner-nav" aria-label="Workspace management"><Link className="button button-primary" href="/dashboard/availability">Manage availability</Link></nav><section className="dashboard-coming"><h2>Your staff workspace</h2><p>Manage your assigned availability here. Owner appointment operations are not available to staff.</p></section></main>}
 const {db,organization,overview}=await getAppointmentOverview();const [{data:orgMedia},{data:progress}]=await Promise.all([db.from("organizations").select("logo_path").eq("id",organization.id).single(),db.from("onboarding_progress").select("staff_profile_id").eq("organization_id",organization.id).maybeSingle()]);const {data:staff}=progress?.staff_profile_id?await db.from("staff_profiles").select("id,display_name,avatar_path").eq("organization_id",organization.id).eq("id",progress.staff_profile_id).maybeSingle():{data:null};const supabaseUrl=getPublicEnvironment().NEXT_PUBLIC_SUPABASE_URL;
 return <main id="main-content" className="dashboard-foundation operations-dashboard">
  <header className="dashboard-header"><div><p className="eyebrow">Owner workspace</p><h1>{organization.name}</h1><p>Operational day: {overview.localDate} · {overview.timezone}</p></div><form action={signOutAction}><button className="button onboarding-secondary">Sign out</button></form></header>
  {query.published==="1"?<div className="publish-success" role="status">Your business passed every publication check and is now live.</div>:null}{query.joined==="1"?<div className="publish-success" role="status">Invitation accepted. Welcome to the team.</div>:null}
  <nav className="owner-nav" aria-label="Workspace management"><Link className="button button-primary" href="/dashboard/appointments">Appointments</Link><Link className="button onboarding-secondary" href="/dashboard/services">Manage services</Link><Link className="button onboarding-secondary" href="/dashboard/team">Manage team</Link><Link className="button onboarding-secondary" href="/dashboard/availability">Manage availability</Link></nav>
  <section aria-labelledby="metrics-heading"><div className="team-section-heading"><div><p className="eyebrow">At a glance</p><h2 id="metrics-heading">Appointment activity</h2></div><span>Business timezone</span></div><div className="operation-metrics"><Metric label="Today" value={overview.today}/><Metric label="Upcoming" value={overview.upcoming}/><Metric label="Completed" value={overview.completed}/><Metric label="Cancelled / no-show" value={overview.cancelled}/></div></section>
  <section className="operation-schedule" aria-labelledby="schedule-heading"><div className="team-section-heading"><div><p className="eyebrow">Next up</p><h2 id="schedule-heading">Upcoming schedule</h2></div><Link href="/dashboard/appointments">View all appointments</Link></div>{overview.schedule.length?<ol>{overview.schedule.map(item=><li key={item.id}><time dateTime={item.startsAt}>{time(item.startsAt,overview.timezone)}</time><div><strong>{item.service}</strong><span>{item.client} · {item.staff}</span></div><Link href={`/dashboard/appointments/${item.id}`}>Open</Link></li>)}</ol>:<div className="service-empty"><h3>No upcoming appointments</h3><p>Confirmed future bookings will appear here.</p></div>}</section>
  <PublicationManager organizationId={organization.id} slug={organization.slug} status={organization.status}/><section className="dashboard-media"><p className="eyebrow">Public presentation</p><h2>Branding and profile media</h2><p>These optional images never change publication status. Only deliberately public presentation media belongs here.</p><MediaControl kind="logo" organizationId={organization.id} currentPath={orgMedia?.logo_path??null} displayName={organization.name} supabaseUrl={supabaseUrl}/>{staff?<MediaControl kind="avatar" organizationId={organization.id} staffId={staff.id} currentPath={staff.avatar_path} displayName={staff.display_name} supabaseUrl={supabaseUrl}/>:null}</section>
 </main>
}
function Metric({label,value}:{label:string;value:number}){return <article><span>{label}</span><strong>{value}</strong></article>}
