"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { bookingPoliciesSchema, businessIdentitySchema, locationSchema } from "./schemas";
import type { OnboardingActionResult } from "./action-result";
function raw(formData:FormData){ return Object.fromEntries(formData.entries()); }
function invalid(error:{flatten():{fieldErrors:Record<string,string[]|undefined>}}):OnboardingActionResult{return{status:"error",message:"Check the highlighted fields.",fields:error.flatten().fieldErrors};}
async function verifiedClient(){const supabase=await createClient();const {data}=await supabase.auth.getUser();if(!data.user?.email_confirmed_at)return null;return supabase;}
export async function saveBusinessIdentity(_:OnboardingActionResult,formData:FormData):Promise<OnboardingActionResult>{const parsed=businessIdentitySchema.safeParse(raw(formData));if(!parsed.success)return invalid(parsed.error);const db=await verifiedClient();if(!db)return{status:"error",message:"Your verified session has expired. Sign in again."};const {error}=await db.rpc("save_onboarding_business_identity",{target_org_id:parsed.data.organizationId,business_name:parsed.data.businessName,public_slug:parsed.data.slug});if(error){if(error.code==="23505")return{status:"error",message:"Choose another business address.",fields:{slug:["That address is already in use."]}};return{status:"error",message:"We could not save this step. Please try again."};}revalidatePath("/onboarding");if(formData.get("intent")==="exit")redirect("/");return{status:"success",message:"Business identity saved.",nextStep:"location"};}
export async function saveLocation(_:OnboardingActionResult,formData:FormData):Promise<OnboardingActionResult>{const parsed=locationSchema.safeParse(raw(formData));if(!parsed.success)return invalid(parsed.error);const db=await verifiedClient();if(!db)return{status:"error",message:"Your verified session has expired. Sign in again."};const d=parsed.data;const {error}=await db.rpc("save_onboarding_location",{target_org_id:d.organizationId,timezone_name:d.timezone,currency_code:d.currency,country:d.countryCode,city_name:d.city,address1:d.addressLine1,address2:d.addressLine2,region_name:d.region,postal:d.postalCode});if(error)return{status:"error",message:"We could not save this step. Check your location details."};revalidatePath("/onboarding");if(formData.get("intent")==="exit")redirect("/");return{status:"success",message:"Location and regional settings saved.",nextStep:"booking-policies"};}
export async function saveBookingPolicies(_:OnboardingActionResult,formData:FormData):Promise<OnboardingActionResult>{const parsed=bookingPoliciesSchema.safeParse(raw(formData));if(!parsed.success)return invalid(parsed.error);const db=await verifiedClient();if(!db)return{status:"error",message:"Your verified session has expired. Sign in again."};const d=parsed.data;const {error}=await db.rpc("save_onboarding_booking_policies",{target_org_id:d.organizationId,lead_minutes:d.minimumLeadMinutes,horizon_days:d.bookingHorizonDays,cancellation_minutes:d.cancellationNoticeMinutes,reschedule_minutes:d.rescheduleNoticeMinutes,interval_minutes:d.slotIntervalMinutes,guests_enabled:d.guestBookingEnabled,terms:d.policyText});if(error)return{status:"error",message:"We could not save these policies. Please review the values."};revalidatePath("/onboarding");if(formData.get("intent")==="exit")redirect("/");return{status:"success",message:"Booking policies saved. The next setup tools arrive in Phase 3B.",nextStep:"staff-profile"};}
