"use server";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import type {ServiceActionResult} from "./action-result";
import {createServiceSchema,parseCurrencyToMinor,serviceAssignmentSchema,serviceStatusSchema,updateServiceSchema} from "./schemas";
function raw(data:FormData){return Object.fromEntries([...data.entries()].filter(([key])=>!key.startsWith("$ACTION_")))}
function invalid(error:{flatten():{fieldErrors:Record<string,string[]|undefined>}}):ServiceActionResult{return{status:"error",message:"Check the highlighted fields.",fields:error.flatten().fieldErrors}}
async function verified(){const db=await createClient();const {data}=await db.auth.getUser();return data.user?.email_confirmed_at?db:null}
async function currencyFor(db:Awaited<ReturnType<typeof createClient>>,organizationId:string){const {data}=await db.from("organizations").select("currency").eq("id",organizationId).maybeSingle();return data?.currency??null}
function refresh(serviceId?:string){revalidatePath("/dashboard");revalidatePath("/dashboard/services");if(serviceId)revalidatePath(`/dashboard/services/${serviceId}`);revalidatePath("/book/[slug]","page")}
export async function createService(_:ServiceActionResult,data:FormData):Promise<ServiceActionResult>{const parsed=createServiceSchema.safeParse(raw(data));if(!parsed.success)return invalid(parsed.error);const db=await verified();if(!db)return{status:"error",message:"Your verified session has expired."};const currency=await currencyFor(db,parsed.data.organizationId);if(!currency)return{status:"error",message:"The organization is unavailable."};const price=parseCurrencyToMinor(parsed.data.price,currency);if(price===null)return{status:"error",message:"Check the highlighted fields.",fields:{price:["Enter a valid non-negative price in the organization currency."]}};const d=parsed.data;const {data:id,error}=await db.rpc("create_managed_service",{target_org_id:d.organizationId,service_name:d.name,service_description:d.description,service_duration:d.durationMinutes,service_buffer:d.bufferMinutes,service_price_minor:price});if(error||!id)return{status:"error",message:"The service could not be created."};refresh(id);redirect(`/dashboard/services/${id}?created=1`)}
export async function updateService(_:ServiceActionResult,data:FormData):Promise<ServiceActionResult>{const parsed=updateServiceSchema.safeParse(raw(data));if(!parsed.success)return invalid(parsed.error);const db=await verified();if(!db)return{status:"error",message:"Your verified session has expired."};const {data:service}=await db.from("services").select("organization_id").eq("id",parsed.data.serviceId).maybeSingle();if(!service)return{status:"error",message:"The service is unavailable."};const currency=await currencyFor(db,service.organization_id);const price=currency?parseCurrencyToMinor(parsed.data.price,currency):null;if(price===null)return{status:"error",message:"Check the highlighted fields.",fields:{price:["Enter a valid non-negative price in the organization currency."]}};const d=parsed.data;const {error}=await db.rpc("update_managed_service",{target_service_id:d.serviceId,service_name:d.name,service_description:d.description,service_duration:d.durationMinutes,service_buffer:d.bufferMinutes,service_price_minor:price});if(error)return{status:"error",message:"The service could not be updated."};refresh(d.serviceId);return{status:"success",message:"Service details saved."}}
export async function changeServiceStatus(_:ServiceActionResult,data:FormData):Promise<ServiceActionResult>{const parsed=serviceStatusSchema.safeParse(raw(data));if(!parsed.success)return invalid(parsed.error);const db=await verified();if(!db)return{status:"error",message:"Your verified session has expired."};const {error}=await db.rpc("set_managed_service_status",{target_service_id:parsed.data.serviceId,desired_status:parsed.data.status});if(error)return{status:"error",message:"The service status could not be changed."};refresh(parsed.data.serviceId);return{status:"success",message:parsed.data.status==="archived"?"Service archived.":"Service activated."}}
export async function changeServiceAssignment(_:ServiceActionResult,data:FormData):Promise<ServiceActionResult>{const parsed=serviceAssignmentSchema.safeParse(raw(data));if(!parsed.success)return invalid(parsed.error);const db=await verified();if(!db)return{status:"error",message:"Your verified session has expired."};const {error}=await db.rpc("set_managed_service_staff",{target_service_id:parsed.data.serviceId,target_staff_id:parsed.data.staffId,assigned:parsed.data.assigned});if(error)return{status:"error",message:"The staff assignment could not be changed."};refresh(parsed.data.serviceId);return{status:"success",message:parsed.data.assigned?"Staff assigned.":"Staff unassigned."}}
