"use client";
/* eslint-disable @next/next/no-img-element -- validated Supabase bucket URLs are runtime tenant data and need an error fallback. */
import {useActionState,useState} from "react";
import {removeAvatar,removeLogo,uploadAvatar,uploadLogo} from "@/features/media/actions";
import {initialMediaResult} from "@/features/media/action-result";
import {initials,PUBLIC_MEDIA_MAX_BYTES,PUBLIC_MEDIA_TYPES,publicMediaUrl,validateMediaFile} from "@/features/media/validation";

export function MediaControl({kind,organizationId,staffId,currentPath,displayName,supabaseUrl}:{kind:"logo"|"avatar";organizationId:string;staffId?:string;currentPath:string|null;displayName:string;supabaseUrl:string}){
 const [brokenPath,setBrokenPath]=useState<string>();const [clientError,setClientError]=useState<string>();const uploadAction=kind==="logo"?uploadLogo:uploadAvatar;const removeAction=kind==="logo"?removeLogo:removeAvatar;
 const [uploadState,uploadForm,pendingUpload]=useActionState(uploadAction,initialMediaResult);const [removeState,removeForm,pendingRemove]=useActionState(removeAction,initialMediaResult);const result=uploadState.status!=="idle"?uploadState:removeState;
 const path=removeState.status==="success"?null:uploadState.status==="success"&&uploadState.path!==undefined?uploadState.path:currentPath;const url=path!==brokenPath?publicMediaUrl(supabaseUrl,path):null;const label=kind==="logo"?"Organization logo":"Staff avatar";
 return <section className="media-control" aria-labelledby={`${kind}-media-title`}><div className="media-preview">{url?<img src={url} alt={`${displayName} ${kind==="logo"?"logo":"profile photo"}`} onError={()=>setBrokenPath(path??undefined)}/>:<span className="generated-avatar" data-testid={`${kind}-fallback`} aria-label={`${displayName} initials`}>{initials(displayName)}</span>}</div><div className="media-control-body"><h3 id={`${kind}-media-title`}>{label} <small>(optional)</small></h3><p>JPEG, PNG, or WebP. Maximum 2 MB. A safe generated filename is used.</p><form action={uploadForm}><input type="hidden" name="organizationId" value={organizationId}/>{staffId?<input type="hidden" name="staffId" value={staffId}/>:null}<label className="media-file-label" htmlFor={`${kind}-file`}>Choose image</label><input id={`${kind}-file`} name="media" type="file" accept={PUBLIC_MEDIA_TYPES.join(",")} required onChange={event=>{const file=event.target.files?.[0];setClientError(file&&!validateMediaFile(file).ok?(validateMediaFile(file) as {ok:false;message:string}).message:undefined)}}/><button className="button button-primary" disabled={pendingUpload||pendingRemove||!!clientError}>{pendingUpload?"Uploading…":path?"Replace image":"Upload image"}</button></form>{path?<form action={removeForm}><input type="hidden" name="organizationId" value={organizationId}/>{staffId?<input type="hidden" name="staffId" value={staffId}/>:null}<button className="button onboarding-secondary" disabled={pendingUpload||pendingRemove}>{pendingRemove?"Removing…":"Remove image"}</button></form>:null}{clientError?<p className="field-error" role="alert">{clientError}</p>:null}{result.message?<p className={`auth-message auth-message-${result.status}`} role={result.status==="error"?"alert":"status"} aria-live="polite">{result.message}</p>:null}<span className="sr-only">Maximum file size {PUBLIC_MEDIA_MAX_BYTES} bytes.</span></div></section>
}
