"use client";
import Link from "next/link";
import { useActionState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { initialOnboardingResult } from "@/features/onboarding/action-result";
import { saveBookingPolicies, saveBusinessIdentity, saveLocation } from "@/features/onboarding/actions";
import type { OnboardingStep } from "@/features/onboarding/model";
type Values={name:string;slug:string;timezone:string;currency:string;country_code:string|null;city:string|null;address_line1:string|null;address_line2:string|null;region:string|null;postal_code:string|null;settings:{minimum_lead_minutes:number;booking_horizon_days:number;cancellation_notice_minutes:number;reschedule_notice_minutes:number;slot_interval_minutes:number;guest_booking_enabled:boolean;policy_text:string|null}};
export function OnboardingForm({step,organizationId,values}:{step:OnboardingStep;organizationId:string;values:Values}){
 const action=step==="business-identity"?saveBusinessIdentity:step==="location"?saveLocation:saveBookingPolicies;
 const [state,formAction,pending]=useActionState(action,initialOnboardingResult);const router=useRouter();
 useEffect(()=>{if(state.status==="success")router.refresh()},[state.status,router]);
 const error=(name:string)=>(state.fields as Record<string,string[]|undefined>|undefined)?.[name]?.join(" ");
 if(!["business-identity","location","booking-policies"].includes(step))return <div className="onboarding-coming"><h2>Saved so far</h2><p>Your draft is safe. Staff, services, availability, review, and publishing continue in Phase 3B.</p><Link className="button button-primary" href="/">Save and exit</Link></div>;
 return <form action={formAction} className="onboarding-form" noValidate>
  <input type="hidden" name="organizationId" value={organizationId}/>
  {step==="business-identity"?<><Field name="businessName" label="Business display name" required defaultValue={values.name==="Untitled business"?"":values.name} autoComplete="organization" error={error("businessName")}/><Field name="slug" label="Public address" required defaultValue={values.slug.startsWith("draft-")?"":values.slug} prefix="serviceflow.local/book/" hint="3–63 lowercase letters, numbers, and single hyphens." error={error("slug")}/></>:null}
  {step==="location"?<><Field name="timezone" label="IANA timezone" required defaultValue={values.timezone} hint="For example, Europe/Bucharest." error={error("timezone")}/><div className="field-row"><Select name="currency" label="Currency" value={values.currency} options={["RON","EUR","USD","GBP"]} error={error("currency")}/><Field name="countryCode" label="Country code" required defaultValue={values.country_code??""} hint="Two-letter ISO code, such as RO." error={error("countryCode")}/></div><Field name="city" label="City" required defaultValue={values.city??""} autoComplete="address-level2" error={error("city")}/><Field name="addressLine1" label="Address line 1 (optional)" defaultValue={values.address_line1??""} autoComplete="address-line1" error={error("addressLine1")}/><Field name="addressLine2" label="Address line 2 (optional)" defaultValue={values.address_line2??""} autoComplete="address-line2" error={error("addressLine2")}/><div className="field-row"><Field name="region" label="Region (optional)" defaultValue={values.region??""} autoComplete="address-level1" error={error("region")}/><Field name="postalCode" label="Postal code (optional)" defaultValue={values.postal_code??""} autoComplete="postal-code" error={error("postalCode")}/></div></>:null}
  {step==="booking-policies"?<><div className="field-row"><NumberField name="minimumLeadMinutes" label="Minimum lead time (minutes)" value={values.settings.minimum_lead_minutes} min={0} max={525600} error={error("minimumLeadMinutes")}/><NumberField name="bookingHorizonDays" label="Booking horizon (days)" value={values.settings.booking_horizon_days} min={1} max={365} error={error("bookingHorizonDays")}/></div><div className="field-row"><NumberField name="cancellationNoticeMinutes" label="Cancellation notice (minutes)" value={values.settings.cancellation_notice_minutes} min={0} max={525600} error={error("cancellationNoticeMinutes")}/><NumberField name="rescheduleNoticeMinutes" label="Reschedule notice (minutes)" value={values.settings.reschedule_notice_minutes} min={0} max={525600} error={error("rescheduleNoticeMinutes")}/></div><NumberField name="slotIntervalMinutes" label="Slot interval (minutes)" value={values.settings.slot_interval_minutes} min={5} max={120} step={5} error={error("slotIntervalMinutes")}/><label className="checkbox-field"><input type="checkbox" name="guestBookingEnabled" defaultChecked={values.settings.guest_booking_enabled}/><span><strong>Allow guest bookings</strong><small>Clients can book without creating an account.</small></span></label><div className="form-field"><label htmlFor="policyText">Policy note (optional)</label><textarea id="policyText" name="policyText" rows={4} defaultValue={values.settings.policy_text??""}/></div></>:null}
  {state.message?<div className={`auth-message auth-message-${state.status}`} role={state.status==="error"?"alert":"status"} aria-live="polite">{state.message}</div>:null}
  <div className="form-actions"><button name="intent" value="exit" className="button onboarding-secondary" disabled={pending}>Save and exit</button><button className="button button-primary" disabled={pending}>{pending?"Saving…":"Continue"}</button></div>
 </form>;
}
function Field({name,label,required=false,defaultValue,hint,error,autoComplete,prefix}:{name:string;label:string;required?:boolean;defaultValue:string;hint?:string;error?:string;autoComplete?:string;prefix?:string}){return <div className="form-field"><label htmlFor={name}>{label} {required?<span aria-hidden="true">*</span>:null}</label>{prefix?<span className="input-prefix"><span>{prefix}</span><input id={name} name={name} required={required} defaultValue={defaultValue} aria-invalid={!!error}/></span>:<input id={name} name={name} required={required} defaultValue={defaultValue} autoComplete={autoComplete} aria-invalid={!!error}/>} {hint?<p className="field-hint">{hint}</p>:null}{error?<p className="field-error" role="alert">{error}</p>:null}</div>}
function NumberField({name,label,value,min,max,step=1,error}:{name:string;label:string;value:number;min:number;max:number;step?:number;error?:string}){return <div className="form-field"><label htmlFor={name}>{label} <span aria-hidden="true">*</span></label><input id={name} name={name} type="number" required defaultValue={value} min={min} max={max} step={step} aria-invalid={!!error}/>{error?<p className="field-error">{error}</p>:null}</div>}
function Select({name,label,value,options,error}:{name:string;label:string;value:string;options:string[];error?:string}){return <div className="form-field"><label htmlFor={name}>{label} <span aria-hidden="true">*</span></label><select id={name} name={name} defaultValue={value}>{options.map(o=><option key={o}>{o}</option>)}</select>{error?<p className="field-error">{error}</p>:null}</div>}
