"use client";
import Link from "next/link";
import { useActionState, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { initialOnboardingResult } from "@/features/onboarding/action-result";
import { completeReview, publishOrganization, saveAvailability, saveBookingPolicies, saveBusinessIdentity, saveLocation, saveService, saveStaffProfile } from "@/features/onboarding/actions";
import { onboardingSteps, type OnboardingStep } from "@/features/onboarding/model";
import { formatMinorPrice, type AvailabilityInterval } from "@/features/onboarding/schemas";

export type OnboardingValues={
 name:string;slug:string;timezone:string;currency:string;country_code:string|null;city:string|null;address_line1:string|null;address_line2:string|null;region:string|null;postal_code:string|null;status:string;
 settings:{minimum_lead_minutes:number;booking_horizon_days:number;cancellation_notice_minutes:number;reschedule_notice_minutes:number;slot_interval_minutes:number;guest_booking_enabled:boolean;policy_text:string|null};
 staff:{display_name:string;bio:string|null;job_title:string|null;is_public:boolean;status:string}|null;
 service:{name:string;description:string|null;duration_minutes:number;buffer_after_minutes:number;price_minor:number;currency:string;status:string}|null;
 availability:AvailabilityInterval[];
};
const weekdays=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
export function OnboardingForm({step,organizationId,values,editing=false}:{step:OnboardingStep;organizationId:string;values:OnboardingValues;editing?:boolean}){
 const action=step==="business-identity"?saveBusinessIdentity:step==="location"?saveLocation:step==="booking-policies"?saveBookingPolicies:step==="staff-profile"?saveStaffProfile:step==="service"?saveService:step==="availability"?saveAvailability:step==="review"?completeReview:publishOrganization;
 const [state,formAction,pending]=useActionState(action,initialOnboardingResult);const router=useRouter();
 useEffect(()=>{if(state.status==="success"){if(editing)router.push("/onboarding");else router.refresh()}},[state.status,editing,router]);
 const error=(name:string)=>(state.fields as Record<string,string[]|undefined>|undefined)?.[name]?.join(" ");
 const currentIndex=onboardingSteps.findIndex(item=>item.key===step);const previous=currentIndex>0?onboardingSteps[currentIndex-1].key:null;
 return <form action={formAction} className="onboarding-form" noValidate>
  <input type="hidden" name="organizationId" value={organizationId}/>
  {step==="business-identity"?<><Field name="businessName" label="Business display name" required defaultValue={values.name==="Untitled business"?"":values.name} autoComplete="organization" error={error("businessName")}/><Field name="slug" label="Public address" required defaultValue={values.slug.startsWith("draft-")?"":values.slug} prefix="serviceflow.local/book/" hint="3–63 lowercase letters, numbers, and single hyphens." error={error("slug")}/></>:null}
  {step==="location"?<><Field name="timezone" label="IANA timezone" required defaultValue={values.timezone} hint="For example, Europe/Bucharest." error={error("timezone")}/><div className="field-row"><Select name="currency" label="Currency" value={values.currency} options={["RON","EUR","USD","GBP"]} error={error("currency")}/><Field name="countryCode" label="Country code" required defaultValue={values.country_code??""} hint="Two-letter ISO code, such as RO." error={error("countryCode")}/></div><Field name="city" label="City" required defaultValue={values.city??""} autoComplete="address-level2" error={error("city")}/><Field name="addressLine1" label="Address line 1 (optional)" defaultValue={values.address_line1??""} autoComplete="address-line1" error={error("addressLine1")}/><Field name="addressLine2" label="Address line 2 (optional)" defaultValue={values.address_line2??""} autoComplete="address-line2" error={error("addressLine2")}/><div className="field-row"><Field name="region" label="Region (optional)" defaultValue={values.region??""} autoComplete="address-level1" error={error("region")}/><Field name="postalCode" label="Postal code (optional)" defaultValue={values.postal_code??""} autoComplete="postal-code" error={error("postalCode")}/></div></>:null}
  {step==="booking-policies"?<><div className="field-row"><NumberField name="minimumLeadMinutes" label="Minimum lead time (minutes)" value={values.settings.minimum_lead_minutes} min={0} max={525600} error={error("minimumLeadMinutes")}/><NumberField name="bookingHorizonDays" label="Booking horizon (days)" value={values.settings.booking_horizon_days} min={1} max={365} error={error("bookingHorizonDays")}/></div><div className="field-row"><NumberField name="cancellationNoticeMinutes" label="Cancellation notice (minutes)" value={values.settings.cancellation_notice_minutes} min={0} max={525600} error={error("cancellationNoticeMinutes")}/><NumberField name="rescheduleNoticeMinutes" label="Reschedule notice (minutes)" value={values.settings.reschedule_notice_minutes} min={0} max={525600} error={error("rescheduleNoticeMinutes")}/></div><NumberField name="slotIntervalMinutes" label="Slot interval (minutes)" value={values.settings.slot_interval_minutes} min={5} max={120} step={5} error={error("slotIntervalMinutes")}/><label className="checkbox-field"><input type="checkbox" name="guestBookingEnabled" defaultChecked={values.settings.guest_booking_enabled}/><span><strong>Allow guest bookings</strong><small>Clients may book without an account once booking launches.</small></span></label><TextArea name="policyText" label="Policy note (optional)" value={values.settings.policy_text??""}/></>:null}
  {step==="staff-profile"?<StaffFields values={values} error={error}/>:null}
  {step==="service"?<ServiceFields values={values} error={error}/>:null}
  {step==="availability"?<AvailabilityFields initial={values.availability} timezone={values.timezone} error={error("intervals")}/>:null}
  {step==="review"?<Review values={values}/>:null}
  {step==="publish"?<Publish values={values}/>:null}
  {state.message?<div className={`auth-message auth-message-${state.status}`} role={state.status==="error"?"alert":"status"} aria-live="polite">{state.message}</div>:null}
  <div className="form-actions">{previous&&step!=="publish"?<Link href={`/onboarding?step=${previous}`} className="button onboarding-secondary">Back</Link>:<button name="intent" value="exit" className="button onboarding-secondary" disabled={pending}>Save and exit</button>}<button className="button button-primary" disabled={pending}>{pending?"Saving…":step==="review"?"Confirm review":step==="publish"?"Publish business":"Continue"}</button></div>
 </form>;
}
function StaffFields({values,error}:{values:OnboardingValues;error:(name:string)=>string|undefined}){const initial=(values.staff?.display_name??values.name).split(/\s+/).map(part=>part[0]).join("").slice(0,2).toUpperCase();return <><div className="staff-intro"><span className="generated-avatar" aria-hidden="true">{initial||"SF"}</span><div><strong>Owner-operator profile</strong><p>This public profile is securely linked to your owner membership.</p></div></div><Field name="staffName" label="Public display name" required defaultValue={values.staff?.display_name??""} autoComplete="name" error={error("staffName")}/><Field name="jobTitle" label="Job title (optional)" defaultValue={values.staff?.job_title??""} error={error("jobTitle")}/><TextArea name="staffBio" label="Short biography (optional)" value={values.staff?.bio??""} error={error("staffBio")}/><p className="field-hint">This first profile is active and public so it can receive the service configured next. No invitation or additional account is created.</p></>}
function ServiceFields({values,error}:{values:OnboardingValues;error:(name:string)=>string|undefined}){return <><Field name="serviceName" label="Service name" required defaultValue={values.service?.name??""} error={error("serviceName")}/><TextArea name="serviceDescription" label="Description (optional)" value={values.service?.description??""} error={error("serviceDescription")}/><div className="field-row"><NumberField name="durationMinutes" label="Duration (minutes)" value={values.service?.duration_minutes??60} min={5} max={480} step={5} error={error("durationMinutes")}/><NumberField name="bufferMinutes" label="Buffer after (minutes)" value={values.service?.buffer_after_minutes??0} min={0} max={240} step={5} error={error("bufferMinutes")}/></div><Field name="price" label={`Price in ${values.currency}`} required defaultValue={values.service?(values.service.price_minor/100).toFixed(2):"0.00"} inputMode="decimal" hint="Stored as integer minor units. Currency comes from your organization." error={error("price")}/><p className="field-hint">The onboarding service is activated, made public, assigned to your owner profile, and uses no payment requirement in this phase.</p></>}
function AvailabilityFields({initial,timezone,error}:{initial:AvailabilityInterval[];timezone:string;error?:string}){const [items,setItems]=useState<AvailabilityInterval[]>(initial.length?initial:[{weekday:1,start:"09:00",end:"17:00"}]);const update=(index:number,key:keyof AvailabilityInterval,value:string)=>setItems(current=>current.map((item,i)=>i===index?{...item,[key]:key==="weekday"?Number(value):value}:item));return <fieldset className="availability-fieldset"><legend>Weekly intervals</legend><p className="field-hint">Times use <strong>{timezone}</strong>. Each interval stays within one local day and uses five-minute increments.</p><input type="hidden" name="intervals" value={JSON.stringify(items)}/><div className="availability-list">{items.map((item,index)=><div className="availability-row" key={index}><Select name={`weekday-${index}`} label="Weekday" value={String(item.weekday)} options={weekdays.map((name,i)=>({label:name,value:String(i+1)}))} onChange={value=>update(index,"weekday",value)}/><Field name={`start-${index}`} label="Start" type="time" required defaultValue={item.start} step={300} onChange={value=>update(index,"start",value)}/><Field name={`end-${index}`} label="End" type="time" required defaultValue={item.end} step={300} onChange={value=>update(index,"end",value)}/><button type="button" className="remove-interval" onClick={()=>setItems(current=>current.filter((_,i)=>i!==index))} aria-label={`Remove ${weekdays[item.weekday-1]} interval`}>Remove</button></div>)}</div>{error?<p className="field-error" role="alert">{error}</p>:null}<button type="button" className="button onboarding-secondary add-interval" onClick={()=>setItems(current=>[...current,{weekday:1,start:"09:00",end:"17:00"}])}>Add interval</button></fieldset>}
function Review({values}:{values:OnboardingValues}){return <div className="review-grid"><ReviewCard title="Business" edit="business-identity"><strong>{values.name}</strong><span>/book/{values.slug}</span></ReviewCard><ReviewCard title="Location & region" edit="location"><strong>{[values.city,values.region,values.country_code].filter(Boolean).join(", ")}</strong><span>{values.timezone} · {values.currency}</span></ReviewCard><ReviewCard title="Booking policies" edit="booking-policies"><strong>{values.settings.booking_horizon_days}-day booking horizon</strong><span>{values.settings.minimum_lead_minutes} minute lead time</span></ReviewCard><ReviewCard title="Owner profile" edit="staff-profile"><strong>{values.staff?.display_name}</strong><span>{values.staff?.job_title||"Owner-operator"}</span></ReviewCard><ReviewCard title="First service" edit="service"><strong>{values.service?.name}</strong><span>{values.service?formatMinorPrice(values.service.price_minor,values.currency):""} · {values.service?.duration_minutes} minutes</span></ReviewCard><ReviewCard title="Availability" edit="availability"><strong>{values.availability.length} weekly interval{values.availability.length===1?"":"s"}</strong><span>{values.timezone}</span></ReviewCard><div className="readiness-card"><strong>Ready for publication checks</strong><p>Publishing revalidates every item transactionally in PostgreSQL. Your business remains a private draft until that succeeds.</p></div></div>}
function ReviewCard({title,edit,children}:{title:string;edit:OnboardingStep;children:React.ReactNode}){return <article className="review-card"><div><h3>{title}</h3><Link href={`/onboarding?step=${edit}`}>Edit</Link></div>{children}</article>}
function Publish({values}:{values:OnboardingValues}){return <div className="publish-ready"><span aria-hidden="true">✓</span><h2>Everything is ready</h2><p>Publishing will make <strong>/book/{values.slug}</strong> visible. Interactive booking remains unavailable until the booking-engine phase.</p><Link href="/onboarding/preview" target="_blank">Preview your persisted draft</Link></div>}
function Field({name,label,required=false,defaultValue,hint,error,autoComplete,prefix,type="text",step,inputMode,onChange}:{name:string;label:string;required?:boolean;defaultValue:string;hint?:string;error?:string;autoComplete?:string;prefix?:string;type?:string;step?:number;inputMode?:"decimal";onChange?:(value:string)=>void}){const input=<input id={name} name={name} type={type} required={required} defaultValue={defaultValue} autoComplete={autoComplete} step={step} inputMode={inputMode} aria-invalid={!!error} onChange={event=>onChange?.(event.target.value)}/>;return <div className="form-field"><label htmlFor={name}>{label} {required?<span aria-hidden="true">*</span>:null}</label>{prefix?<span className="input-prefix"><span>{prefix}</span>{input}</span>:input}{hint?<p className="field-hint">{hint}</p>:null}{error?<p className="field-error" role="alert">{error}</p>:null}</div>}
function NumberField({name,label,value,min,max,step=1,error}:{name:string;label:string;value:number;min:number;max:number;step?:number;error?:string}){return <div className="form-field"><label htmlFor={name}>{label} <span aria-hidden="true">*</span></label><input id={name} name={name} type="number" required defaultValue={value} min={min} max={max} step={step} aria-invalid={!!error}/>{error?<p className="field-error">{error}</p>:null}</div>}
function Select({name,label,value,options,error,onChange}:{name:string;label:string;value:string;options:(string|{label:string;value:string})[];error?:string;onChange?:(value:string)=>void}){return <div className="form-field"><label htmlFor={name}>{label} <span aria-hidden="true">*</span></label><select id={name} name={name} defaultValue={value} onChange={event=>onChange?.(event.target.value)}>{options.map(option=>{const item=typeof option==="string"?{label:option,value:option}:option;return <option key={item.value} value={item.value}>{item.label}</option>})}</select>{error?<p className="field-error">{error}</p>:null}</div>}
function TextArea({name,label,value,error}:{name:string;label:string;value:string;error?:string}){return <div className="form-field"><label htmlFor={name}>{label}</label><textarea id={name} name={name} rows={4} defaultValue={value} aria-invalid={!!error}/>{error?<p className="field-error">{error}</p>:null}</div>}
