import {describe,expect,it} from "vitest";import {createBlockSchema,createWeeklySchema,intervalsOverlap,updateWeeklySchema} from "@/features/availability/schemas";import {formatZoned,utcToLocalInput,zonedLocalToUtc} from "@/features/availability/time";import {initialAvailabilityResult,type AvailabilityActionResult} from "@/features/availability/action-result";
const staff="13000000-0000-4000-8000-000000000102";
describe("Phase 4C availability",()=>{
 it("validates five-minute ordered weekly intervals",()=>{expect(createWeeklySchema.safeParse({staffProfileId:staff,weekday:"2",start:"09:00",end:"12:30"}).success).toBe(true);expect(createWeeklySchema.safeParse({staffProfileId:staff,weekday:"2",start:"12:00",end:"09:00"}).success).toBe(false);expect(createWeeklySchema.safeParse({staffProfileId:staff,weekday:"2",start:"09:03",end:"10:00"}).success).toBe(false)});
 it("rejects forged and surplus identifiers",()=>{expect(createWeeklySchema.safeParse({staffProfileId:"forged",weekday:1,start:"09:00",end:"10:00"}).success).toBe(false);expect(updateWeeklySchema.safeParse({intervalId:staff,weekday:1,start:"09:00",end:"10:00",expectedUpdatedAt:"bad",organizationId:staff}).success).toBe(false)});
 it("detects overlaps but permits adjacency",()=>{expect(intervalsOverlap([{weekday:1,start:"09:00",end:"11:00"},{weekday:1,start:"10:00",end:"12:00"}])).toBe(true);expect(intervalsOverlap([{weekday:1,start:"09:00",end:"11:00"},{weekday:1,start:"11:00",end:"12:00"}])).toBe(false)});
 it("bounds internal block labels",()=>{const base={staffProfileId:staff,startsAt:"2026-09-01T09:00",endsAt:"2026-09-01T10:00"};expect(createBlockSchema.safeParse({...base,reason:"Internal only"}).success).toBe(true);expect(createBlockSchema.safeParse({...base,reason:"x".repeat(501)}).success).toBe(false)});
 it("converts unambiguous organization-local times",()=>{expect(zonedLocalToUtc("2026-01-15T10:00","Europe/Bucharest")).toBe("2026-01-15T08:00:00.000Z");expect(utcToLocalInput("2026-01-15T08:00:00.000Z","Europe/Bucharest")).toBe("2026-01-15T10:00");expect(formatZoned("2026-01-15T08:00:00.000Z","Europe/Bucharest")).toContain("10:00")});
 it("rejects DST gaps and ambiguous wall times",()=>{expect(zonedLocalToUtc("2026-03-29T03:30","Europe/Bucharest")).toBeNull();expect(zonedLocalToUtc("2026-10-25T03:30","Europe/Bucharest")).toBeNull()});
 it("keeps stable typed action results",()=>{const result:AvailabilityActionResult={status:"error",code:"STALE",message:"Reload."};expect(initialAvailabilityResult).toEqual({status:"idle"});expect(result.code).toBe("STALE")});
});
