import {describe,expect,it} from "vitest";
import {createServiceSchema,currencyFractionDigits,formatServicePrice,normalizeServiceForm,parseCurrencyToMinor,serviceAssignmentSchema,serviceStatusSchema,updateServiceSchema} from "@/features/services/schemas";
import {safeServiceError} from "@/features/services/errors";
const org="10000000-0000-4000-8000-000000000001",service="12000000-0000-4000-8000-000000000101",staff="13000000-0000-4000-8000-000000000102";
describe("Phase 4A service validation",()=>{
 it("parses two-decimal prices without floating-point storage",()=>{expect(currencyFractionDigits("EUR")).toBe(2);expect(parseCurrencyToMinor("125.50","EUR")).toBe(12550);expect(parseCurrencyToMinor("0","RON")).toBe(0);expect(parseCurrencyToMinor("12.345","GBP")).toBeNull();expect(parseCurrencyToMinor("-1","USD")).toBeNull()});
 it("supports zero-decimal currencies generically",()=>{expect(currencyFractionDigits("JPY")).toBe(0);expect(parseCurrencyToMinor("125","JPY")).toBe(125);expect(parseCurrencyToMinor("125.00","JPY")).toBeNull()});
 it("formats minor units through currency metadata",()=>{expect(formatServicePrice(12550,"EUR","en-US")).toContain("125.50");expect(formatServicePrice(125,"JPY","en-US")).toContain("125")});
 it("enforces text, duration, buffer and price field bounds",()=>{const valid={organizationId:org,name:"Fictional Session",description:"A fictional service.",durationMinutes:"60",bufferMinutes:"15",price:"90.00"};expect(createServiceSchema.safeParse(valid).success).toBe(true);expect(createServiceSchema.safeParse({...valid,durationMinutes:"4"}).success).toBe(false);expect(createServiceSchema.safeParse({...valid,bufferMinutes:"241"}).success).toBe(false);expect(createServiceSchema.safeParse({...valid,name:""}).success).toBe(false);expect(createServiceSchema.safeParse({...valid,unknown:"forged"}).success).toBe(false)});
 it("requires safe resource identifiers",()=>{expect(updateServiceSchema.safeParse({serviceId:service,name:"Safe",description:"",durationMinutes:30,bufferMinutes:0,price:"1.00"}).success).toBe(true);expect(updateServiceSchema.safeParse({serviceId:"forged",name:"Safe",description:"",durationMinutes:30,bufferMinutes:0,price:"1.00"}).success).toBe(false);expect(serviceAssignmentSchema.safeParse({serviceId:service,staffId:staff,assigned:"true"}).success).toBe(true);expect(serviceStatusSchema.safeParse({serviceId:service,status:"deleted"}).success).toBe(false)});
 it("normalizes deterministic form text without changing numeric authority",()=>expect(normalizeServiceForm({name:"  Fictional Session  ",description:"  Notes  ",durationMinutes:60,bufferMinutes:5,price:" 10.00 "})).toEqual({name:"Fictional Session",description:"Notes",durationMinutes:60,bufferMinutes:5,price:"10.00"}));
 it("maps database failures without leaking details",()=>expect(safeServiceError("assignment",{message:"private database detail"})).toBe("The staff assignment could not be changed."));
});
